### ISSUE TITLE
Discover features fails in case Jicofo connected to openfire

### ISSUE THREAD

**Issue by Kidav** [jitsi/jicofo#10]
After focus successfully allocated in the conference room and all participants connected to the jitsi meet conference in the log I see :

> INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.memberPresenceChanged().123 Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@65e4122f member=org.jitsi.impl.protocol.xmpp.ChatMemberImpl@484d7bbe]
> INFO: [38] org.jitsi.jicofo.JitsiMeetConference.onMemberJoined().383 Member 7749358@group.conference.host/14c51793475 joined.
> INFO: [38] org.jitsi.jicofo.JitsiMeetConference.inviteChatMember().432 Added participant for: 7749358@group.conference.host/14c51793475
> SEVERE: [45] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.error() No response from the server.:
> No response from the server.:
>         at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:445)
>         at net.java.sip.communicator.impl.protocol.jabber.ScServiceDiscoveryManager.discoverInfo(ScServiceDiscoveryManager.java:569)
>         at net.java.sip.communicator.impl.protocol.jabber.ScServiceDiscoveryManager.discoverInfo(ScServiceDiscoveryManager.java:494)
>         at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.getEntityFeatures(XmppProtocolProvider.java:425)
>         at org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures(OpSetSimpleCapsImpl.java:60)
>         at org.jitsi.jicofo.util.DiscoveryUtil.discoverParticipantFeatures(DiscoveryUtil.java:82)
>         at org.jitsi.jicofo.JitsiMeetConference.discoverFeaturesAndInvite(JitsiMeetConference.java:462)
>         at org.jitsi.jicofo.JitsiMeetConference.access$000(JitsiMeetConference.java:42)
>         at org.jitsi.jicofo.JitsiMeetConference$1.run(JitsiMeetConference.java:447)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>         at java.lang.Thread.run(Thread.java:745)
> SEVERE: [45] org.jitsi.jicofo.util.DiscoveryUtil.discoverParticipantFeatures().85 Failed to discover features for 7749358@group.conference.host/14c51793475 assuming default feature set.

as result Jicofo don't get rtcp-mux feature and ssltcp candidates can't be generated. This happens only when Jicofo as component connected to openfire, with prosody works as expecped.

p.s.
Was applied hack in src/org/jitsi/jicofo/util/DiscoveryUtil.java

> static public List<String> getDefaultParticipantFeatureSet() 
> .....
>          features.add(FEATURE_SCTP);
> -        //
> -        features.add(FEATURE_RTCP_MUX);
> -        features.add(FEATURE_RTP_BUNDLE);
> -        //
>        return features;

and now ssltcp candidates generated, but jigasi won't work in this case 

Any suggestions to get focus discover features

**Comment by nemobis** [comment]
I posted some info about a similar (?) log line at https://community.jitsi.org/t/jitsi-meet-server-stuck-on-reconnecting-time-to-time-with-this-new-jicofo-logs/16119/7

**Comment by bgrozev** [comment]
Outdated
