### ISSUE TITLE
Whole bridge terminates upon Unknown endpoint jvb error

### ISSUE THREAD

**Issue by mykhailo-ua** [jitsi/jicofo#1047]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When a participant has network problems and his endpoint is expired on jvb, when he is back online and send any update (which happened while he was offline) then jicofo receives Unknown endpoint error from jvb and invalidate whole bridge and then re-invite all the participants.
---
## Current behavior
When participant's endpoint is expired on jvb and he is not kicked out from the conference by timeout then with sending any update (which happened while he was offline) jicofo would receive Unknown endpoint error from jvb and invalidate whole bridge and then re-invite all the participants.
---
## Expected Behavior
Only the invalid endpoint is removed from the bridge and participant re-invited.
---
## Possible Solution
To not invalidate the whole bridge but rather endpoint when processing [sendRequest iq](https://github.com/jitsi/jicofo/blob/0e041934124190cdb5a9950df4807d68a23e69d4/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt#L290) for [updateParticipant](https://github.com/jitsi/jicofo/blob/0e041934124190cdb5a9950df4807d68a23e69d4/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt#L142) and jvb triggers [Unknown endpoint error](https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/kotlin/org/jitsi/videobridge/colibri2/Colibri2ConferenceHandler.kt#L199)
---
## Steps to reproduce
- start the conference from any device and use it to keep the meeting alive. (used mobile phone)
- join the same meeting with another participant from another device, but make sure that both microphone and camera are off when joining. (used laptop)
- Disconnect the wifi on the laptop for 80 seconds
- Before switching back wifi on laptop turn the microphone on.
- Check the JS console on laptop, it should contain a message about “focus disconnect reason=moving”
![Screenshot 2023-02-15 at 17 50 04](https://user-images.githubusercontent.com/104766779/219102663-d6acd514-dcea-4339-9903-8b41a284659e.png)
---
# Environment details
https://meet.jit.si/
---

**Comment by bgrozev** [comment]
Makes sense. I think there's two parts to the solution:
1. Adding a [Colibri2Error](https://github.com/jitsi/jitsi-xmpp-extensions/blob/master/src/main/java/org/jitsi/xmpp/extensions/colibri2/Colibri2Error.java) with a new UNKNOWN_ENDPOINT Reason to error responses from the bridge.
2. Recognizing these errors in jicofo and handling them differently (only re-invite that single endpoint)

**Comment by bgrozev** [comment]
Item_not_founds is fine, as long as it also has a colibri2 error extension specifying that it's about an endpoint

**Comment by mykhailo-ua** [comment]
> Item_not_founds is fine, as long as it also has a colibri2 error extension specifying that it's about an endpoint

do we need return specific endpoint id from the jvb?
- how to include? Is it possible to use Colibri2Endpoint extension like
 ![Screenshot 2023-02-17 at 17 34 11](https://user-images.githubusercontent.com/104766779/219711536-79f5ca18-885c-4d32-905c-daee6116d584.png)
- because there some batch operations where multiple endpoints can be used 
![Screenshot 2023-02-17 at 17 35 23](https://user-images.githubusercontent.com/104766779/219711688-218b02ee-4803-4012-b528-4ab3d7c4cab4.png)
![Screenshot 2023-02-17 at 17 43 20](https://user-images.githubusercontent.com/104766779/219713223-3877b92a-af19-44ca-9fc0-f3c5bf27b8a1.png)
- jvb will abort on the first unknown endpoint so will not work anyway with multiple endpoints -  https://github.com/jitsi/jitsi-videobridge/blob/4bbb81e23e779d948d6c92d54315ea282cb86598/jvb/src/main/kotlin/org/jitsi/videobridge/colibri2/Colibri2ConferenceHandler.kt#L72

**Comment by mykhailo-ua** [comment]
Added first pr change for jitsi-xmpp-extension - https://github.com/jitsi/jitsi-xmpp-extensions/pull/93

**Comment by bgrozev** [comment]
The PRs have been merged now, thanks @mykhailo-ua !
