### ISSUE TITLE
jicofo fails to respond to server pings

### ISSUE THREAD

**Issue by gardenia** [jitsi/jicofo#112]
it seems that jicofo has 2 channels to the XMPP server.  the first as component, and the second as a regular XMPP user (username: focus).

in the latter case I am seeing the focus user getting kicked due to failure to respond to server pings when the server is ejabberd.  it looks to me that there is no code in jicofo to respond to pings on that XMPP channel (there is however on the component channel).

I realize that jicofo is by default deployed with prosody and I have ascertained that prosody does not send server-to-client pings, it responds only to client pings, which would explain why users using prosody as the XMPP server would not have this problem.

ejabberd, however, sends server-to-client pings as well as responding to client-to-server pings.

since the connection is closed cleanly by ejabberd (i.e. when the server-to-client ping is not responded to and ejabberd deems that the user has gone away and closes the connection) in this case smack/jicofos reconnection logic does not trigger and so jicofo just stays disconnected indefinitly.

I have attached a sketch of a patch to add responses to server pings.  I realize there is a KeepAliveManager I could have leveraged here but I had a mismatch with the serviceName so it was simpler in my case to just add a patch inline.  it is more to give a general idea than a final proposed patch.

have I missed anything obvious here?  is this handled by some setting I've missed?

ASIDE: a quick note on why this problem only started happeneing / came to light: in ejabberd versions less than 16.04 there was a bug in ejabberd whereby it failed to send the stream trailer before closing the connection (when stream management was disabled, as it is in smack 3.x used by jicofo).  I was previously using a version of ejabberd with the missing trailer bug but due to the bug the connection was closed without the stream trailer this caused an exception to be caught by Smack (in PacketReader) and seemed like a "close with error" scenario which allowed jicofos reconnection logic to kick-in and so the ejabberd bug and the jicofo lack of ping responses conspired to allow focus to mostly be connected to the server, albeit with frequent kicks/reconnects.  since this (ejabberd trailer) bug has been fixed the connection is no longer deemed to have been closed in error and so now jicofo/smack sees no need to try to reconnect.

[jicofo_ping_patch.txt](https://github.com/jitsi/jicofo/files/438316/jicofo_ping_patch.txt)

**Comment by mechazod** [comment]
@gardenia where did you run your jicofo service?

**Comment by gardenia** [comment]
@mechazod I'm not sure I know what you mean by "where" so apologies if I have missed the point.

but in terms of the system:

Debian Linux (64 bit)
Open JDK 7
ejabberd 16.04 

I am also using jitsi-videobridge

**Comment by pabloab** [comment]
On an Ubuntu 18.04 I had installed `jitsi-meet` and then uninstalled (with `apt-get purge`), removing also `sources.list.d/jitsi-stable.list` (`dpkg -l | grep "^ji"` returns nothing). I suspect that is the cause now `systemctl --type service --state failed` list `jicofo.service service` as failed. Apparently it left something not removed: `journalctl --unit jicofo.service` return `jicofo[2836]: Daemon not executable: /usr/share/jicofo/jicofo.sh` (that script it doesn't exist).

**Comment by bgrozev** [comment]
outdated
