### ISSUE TITLE
Failed to start jicofo

### ISSUE THREAD

**Issue by eqnull7** [jitsi/jicofo#1120]
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: No suppliers found a value:
  org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: Key 'org.jitsi.jicofo.FOCUS_USER_DOMAIN' not found in source 'sip communicator props'
  org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: Key 'jicofo.xmpp.client.domain' not found in source 'typesafe config (reloaded 1 times)'
        at org.jitsi.metaconfig.supplier.FallbackSupplier.doGet(FallbackSupplier.kt:57)

**Comment by bgrozev** [comment]
Your configuration file is missing a required property (jicofo.xmpp.client.domain).

**Comment by SchoolGuy** [comment]
I had the same error message. In my case I was missing the Java sysopt `-Dconfig.file=/etc/jitsi/jicofo/jicofo.conf`. After I added this to the systemd service jicofo started just fine.
