### ISSUE TITLE
Request to allow to download binaries

### ISSUE THREAD

**Issue by coresh** [jitsi/jicofo#134]
Please provide us with ready-solution for jifoco repository like existed for jitsi-videobridge:

https://download.jitsi.org/jitsi-videobridge

Should be useful to auto allocate bulds to e.g: 
https://download.jitsi.org/jicofo

Thanks

**Comment by damencho** [comment]
Please use the mailinglist for questions.

There is already debian builds for jicofo:
https://download.jitsi.org/stable/ and https://download.jitsi.org/unstable/. 
If you want you can always checkout jicofo soruce code and execute:
mvn -U clean package -DskipTests -Dassembly.skipAssembly=false
And this will create archives for different operating systems that you can use.
