### ISSUE TITLE
Local signaling

### ISSUE THREAD

**Issue by markreg** [jitsi/jicofo#14]
I would like to know if it's possible for jicofo to maintain a single Jingle connection for all conference rooms and participants to a localhost server

The way my app is architected, the clients send their SDP through a secure websocket channel and the app then sends this SDP to a custom MCU which then returns an SDP which the app broadcasts out to all intended receivers. Then the receivers proceed to stream directly from the MCU over DTLS-SRTP.

My tests with Jitsi Videobridge in Jitsi Meet have shown greater stability and quality than our in-house MCU and therefore, I'd like to try to integrate it into the app.

Thanks

**Comment by paweldomas** [comment]
Hi,

By Jingle connection do you mean single Jingle session or single XMPP connection to the server ?

**Comment by markreg** [comment]
Multiple Jingle sessions are ok as long as they can be multiplexed into the same XMPP connection. Ideally, I want to broker all XMPP communication on the back-end via a single connection from an app server (node.js or Go) to Jitsi Conference Focus and keep the browser JS client focused on dealing with SDPs only.

The other part of the equation is that I would also need to re-architect XML DOM node creation/manipulation or inject JSDOM as a dependency, although I hope there's a simpler solution that I'm missing.

**Comment by hitmanperfect** [comment]
hi,i'm trying to use org.jivesoftware.smack.XMPPConnection to connect to jicofo server on the android device ,and  result is that the web browser page can show my name,but the jingleIQ I received is not complete as the web,lack some source  and fingerPrint,can u help me?
my email is lzqwhhit@gmail.com and i am sorry for my poor english，thanks for your help!

**Comment by paweldomas** [comment]
Make sure that your client advertises all of the features listed here:
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/strophe.jingle.js#L28

Also please use our "dev" mailing list for asking questions.

**Comment by hitmanperfect** [comment]
All of these  features are added .but the label of  fingerprint is still lacking ,the data is like this:
89:EF:D9:2A:22:D0:50:CB:0D:8C:6F:61:63:5A:4E:B9:E4:98:43:62,there is no <fingerprint > information
