### ISSUE TITLE
nack pli

### ISSUE THREAD

**Issue by gpolitis** [jitsi/jicofo#16]
moved from https://github.com/jitsi/jitsi-meet/issues/81

Just noticed that chrome 35 includes a
a=rtcp-fb:100 nack pli
line in addition to the nack one (is that legal even?)

This is currently not in
https://github.com/jitsi/jitsi-meet/blob/master/libs/colibri/colibri.focus.js#L297
(which I think is from chrome 33)

**Comment by gpolitis** [comment]
FF doesn't care about what we include in the offer, it sends PLIs. Tested with FF 37, 38, 39. We should probably add this line. I think Chrome behaves correctly though, i.e. it doesn't send PLIs when they're not signaled, it relies on NACKs.

**Comment by gpolitis** [comment]
@bgrozev this could potentially affect NACK termination if, by enabling this line, Chrome favors PLI instead of NACKs. In theory, they're two different things and shouldn't clash but I'm pinging you just in case this breaks something in practice.

**Comment by fippo** [comment]
i've been using it for months and not seen anything that breaks

**Comment by paweldomas** [comment]
Thanks ! Included in https://github.com/jitsi/jicofo/commit/c7af700a2399f21661db3fbb7af2c0890860bd7c
