### ISSUE TITLE
Do a periodic check when JVB has been lost

### ISSUE THREAD

**Issue by linkmauve** [jitsi/jicofo#161]
Hi,

Yesterday my JVB had an error (too many open file descriptors, which I will investigate), after which Jicofo stopped any communication with it, as per these logs:
```
Jicofo 2017-01-27 18:41:58.015 AVERTISSEMENT: [98] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: videobridge.jabberfr.org error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><
text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Failed to acquire DatagramSocket specific to STUN communication</text></error>
Jicofo 2017-01-27 18:41:58.015 INFOS: [38] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().192 Removing JVB: videobridge.jabberfr.org
Jicofo 2017-01-27 18:41:58.016 INFOS: [38] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: videobridge.jabberfr.org
```

I also noticed that if I restart JVB without then restarting Jicofo, it will also remove this component and then do absolutely nothing.

Retrying after a few seconds (or exponentially and capped) would be a nice improvement to prevent that kind of issue from taking down the service.

**Comment by damencho** [comment]
Which jvb version is this?

Jicofo should check for new jvbs up to one minute, you need to give it some time.

**Comment by linkmauve** [comment]
I cannot reproduce anymore, I’m closing this issue but will reopen if anything new comes up. Thanks. :)
