### ISSUE TITLE
“Feature list changed for” message printed at every check when updating a component

### ISSUE THREAD

**Issue by linkmauve** [jitsi/jicofo#188]
After restarting [biboumi](https://biboumi.louiz.org/) with a newer version, Jicofo prints this message every 30s:
```
Jicofo 2017-04-14 15:44:05.310 GRAVE: [107] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().279 Feature list changed for: irc.jabberfr.org
```

It should update the cached feature list once and then stop thinking this other component changed again.

**Comment by paweldomas** [comment]
It is supposed to update the cached feature list. Are you able to debug this code ?
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java#L273

**Comment by bgrozev** [comment]
Outdated
