### ISSUE TITLE
Secure domain Eror

### ISSUE THREAD

**Issue by rubakds** [jitsi/jicofo#191]
Installed on the installation: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
I made the following instructions: https://github.com/jitsi/jicofo#secure-domain

After that, I have a message when I try to create a room:
"Oops! Something went wrong and we could not connect to the conference: connection.otherError"
And in the log (/var/log/jitsi/jicofo.log) is empty (It is not empty, but there will not appear during this time of recording.)

Here is my config (where x.x.x.x = ip adress (I do not have a domain)) 
/etc/prosody/conf.avail/x.x.x.x.cfg.lua  https://pastebin.com/Bq0mYsF0
/etc/jitsi/meet/x.x.x.x-config.js (Excerpt)  https://pastebin.com/0sD03J3U
 /etc/jitsi/jicofo/sip-communicator.properties https://pastebin.com/DL3xzaXg

Tell me I'm doing this wrong, or I have to do something else?

**Comment by paweldomas** [comment]
Strange /var/log/jitsi/jicofo.log should not be empty

**Comment by rubakds** [comment]
I wrote via google.translate.
It is not empty, but there will not appear during this time of recording.
