### ISSUE TITLE
Make unmuting of participants allowed via config

### ISSUE THREAD

**Issue by michaelkrog** [jitsi/jicofo#197]
It is hardcoded into the system that the moderator can mute, but not unmute, participants. Furthermore the participant can allways mute and unmute himself.
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java#L1539

It would be nice if these hardcoded decisions were configurable. We are building a conference system in which we do not want the participants to be able to unmute themselves - only the moderator is allowed to give "talk time" to a specific participant.

Would a pullrequest for such a feature be welcomed or is it out of scope for this project?

**Comment by damencho** [comment]
Hi, this feature is not on our roadmap, but we will be happy to review any PR on the subject.
I think, this feature also needs changes in the UI.

**Comment by michaelkrog** [comment]
> this feature also needs changes in the UI.
Indeed. This will be for more special corner cases. 

We are building our UI upon lib-jitsi-meet because we need a special use case. We have an audio-only system today using Asterisk with up to 300 conferences and 2800 participants in conferences at peak-times. Almost all of them are elderly people that cannot attend the conferences in person because of age or health.

During the conference a tech-guy acts the moderator and will decide who is entitled to give a comment - not the participant himself. A participant can only raise the hand to notify the tech-guy. The tech-guy hence does both the muting an unmuting of participants. This is also to make the system easier to use for the elderly people så they have just 2 buttons in the UI: one for raising their hand and one for leaving the conference.

**Comment by emcho** [comment]
I'd like to raise a flag here. Lack of this ability is intentional as it has privacy and usability applcations. So a PR for this would have to come with the feature off by default

**Comment by michaelkrog** [comment]
@emcho I understand that. What I meant by making it configurable was keeping the current model as default, but making it possible to change it for specific installations.

It is okay with me to keep this issue closed. We are building a new UI's anyways so we can work around it by 1) not having UI for unmuting in participant-clients and 2) sending events to the participant-clients in order for them to unmute themselves when moderator decides to.
