### ISSUE TITLE
Implementing OpenID Connect authentication

### ISSUE THREAD

**Issue by HamzaKhait** [jitsi/jicofo#208]
Dear All,

As I mentioned in the mailing list http://lists.jitsi.org/pipermail/dev/2017-July/034204.html I would like to implement a new authentication feature using OpenID Connect in order to make it work with the OIDC provider FranceConnect.

Before starting this work, I'd like to have some clarifications about developing and adding a new module. Thus I have a couple of questions : 
- Which files should I exactly modify to make it work ? 
- Is there any documentation on how to add new features to Jitsi Meet/Jicofo?

Any help would be greatly appreciated.

Hamza

**Comment by venkatesh-phenompeople** [comment]
Hey what is the status of this issue have you resolved it.

**Comment by d3hof** [comment]
Anyone still proceeding this approach?

**Comment by TBG-FR** [comment]
For those interested :wink: https://community.jitsi.org/t/improving-jitsi-authentication/108753

**Comment by bgrozev** [comment]
Discuss on the community forum
