### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by swapnilbagadia** [jitsi/jicofo#21]
When does jicofo send first IQ packet to videobridge ?

**Comment by paweldomas** [comment]
It is sending it here:

https://github.com/jitsi/jicofo/blob/master/src/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java#L140

More sources come from Jitsi:

https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/impl/protocol/jabber/extensions/colibri/ColibriBuilder.java

**Comment by swapnilbagadia** [comment]
Thanks a lot :+1:
