### ISSUE TITLE
H264 doesn't work in Chrome

### ISSUE THREAD

**Issue by YMIndustries** [jitsi/jicofo#225]
Recently I noticed that h264 conferences don't work in Google Chrome. It seems this issue has been [known for a while](https://github.com/jitsi/jitsi-meet/issues/877#issuecomment-269054479) and is caused by a case sensitivity issue with Chrome.

Steps to reproduce:
1. Set up a Jitsi Meet environment using the [Quick Install](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) guide
2. In /etc/jitsi/meet/jitsi.example.com-config.js, add `preferH264: true`
3. Using two browsers, at least one of them Google Chrome (tested in 60.0.3112.113), navigate to the Jitsi Meet domain and observe that the video call never starts.

I'm happy to contribute a fix for this myself, but I'm not sure where Constants.H264 is defined. I'm very new to Java.

EDIT: I found it in jitsi/libjitsi /src/org/jitsi/service/neomedia/codec/Constants.java. Maybe this issue should be against that project instead?

**Comment by gpolitis** [comment]
@YMIndustries I just tried on latest Chrome stable (62.0.3202.75) both in p2p mode and in multi-party mode and it works correctly whether it is lower or upper case.

Could you please try again with latest? I'm wondering whether this is an issue with older Chrome versions only, or whether there's an issue with your config.js

**Comment by jiyeyuran** [comment]
Multi-party won't work if adding `preferH264: true` in config.js (not in p2p section), even add `disableSimulcast: true`. H264 is preferred because simulcast is not nesssary in low resolution situation.

**Comment by gpolitis** [comment]
@jiyeyuran I'm sorry, but I'm not following. Could you please elaborate a little?

**Comment by jiyeyuran** [comment]
@gpolitis I want use h264 in multi-party conference. It doesn't work if adding `preferH264: true` in config.js.
You can try use chrome (chrome 62 works, but the quality is very poor): 
`https://meet.jit.si/demotest#config.preferH264=true&config.p2p.enabled=false&config.disableSimulcast=true`

**Comment by gpolitis** [comment]
I just tried using the URL you pasted and it works on 62.0.3202.89 (latest stable). Which version of Chrome are you using?

**Comment by jiyeyuran** [comment]
@gpolitis I tested on Chrome 53/55/61 (no video, audio is ok). Chrome 62 works, but the quality is very poor.

**Comment by gpolitis** [comment]
@paweldomas could you please take a look?
