### ISSUE TITLE
no sound without p2p mode

### ISSUE THREAD

**Issue by dreaminglwj** [jitsi/jicofo#250]
p2p: {
        // Enables peer to peer mode. When enabled the system will try to
        // establish a direct connection when there are exactly 2 participants
        // in the room. If that succeeds the conference will stop sending data
        // through the JVB and use the peer to peer connection instead. When a
        // 3rd participant joins the conference will be moved back to the JVB
        // connection.
        enabled: true,

        // Use XEP-0215 to fetch STUN and TURN servers.
        // useStunTurn: true,

        // The STUN servers that will be used in the peer to peer connections
        stunServers: [
            { urls: 'stun:stun.l.google.com:19302' },
            { urls: 'stun:stun1.l.google.com:19302' },
            { urls: 'stun:stun2.l.google.com:19302' }
        ],

if i change  enabled: true    to   enabled: false  no sound and video transfered

**Comment by gpolitis** [comment]
@dreaminglwj do you have a properly configured bridge connected to jicofo?

**Comment by dreaminglwj** [comment]
two points:
1.https://github.com/jitsi/jitsi-meet/issues/2326  this may help
2.if your server is cloud server, like ali cloud. ensure your server contain a network card that cat connect to the public network directly.
