### ISSUE TITLE
Does Jitsi have a webhook?

### ISSUE THREAD

**Issue by pekubu** [jitsi/jicofo#259]
I want to know when a user used the website. For example, when someone joins, jitcofo will send a request to my website, similar to when a user exits the room. How to implement it?
Thanks everyone.

**Comment by listen-lavender** [comment]
Do you find it?

**Comment by listen-lavender** [comment]
Do you find it? @pekubu

**Comment by Stalinko** [comment]
It would be a really good feature.
I'm integrating jitsi into my website and I need a way for my website to know actual count of guests in the room or at least whether it's live or empty.

**Comment by zoernert** [comment]
For me I just wanted to get a message via telegram every time a room is created. So what I did was a bit of shell scripting using [telegram-send](https://pypi.org/project/telegram-send/) which gets called by `/usr/bin/roommonitor` : 

```shell
#!/bin/sh

telegram-send `( tail -F -n0 /var/log/jitsi/jicofo.log & ) | grep -m1 "Created new focus for" `

sleep 5

nohup /usr/bin/roommonitor &

```

Might be a good starting point for even more complex monitorings.

**Comment by Stalinko** [comment]
@zoernert this is only when you host jitsi on own server, isn't it? For those who use public server the question is still open.

**Comment by feklee** [comment]
@Stalinko The iframe [Jitsi API][1] does have events, such as [participantJoined][2]. I am investigating that for making one PC joining our meetings aware of what is going on.

[1]: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
[2]: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#participantjoined

**Comment by maglub** [comment]
Hi,

Thanks for the idea. I did something similar for the dockerized version to "mine the logs" and send notifications.

I have a small script that allows me to send messages to Slack over a pipe, calling it "slack_pipe". The implementation of that is a bit out of scope.

The dockerized jitsi has a handful of containers, jicofo is one of them:

```
$ docker ps | grep jicofo | awk '{print $NF}'
docker-jitsi-meet-stable-5963_jicofo_1
```

There are no "on disk" logs, but you get the log output per `docker logs docker-jitsi-meet-stable-5963_jicofo_1`, so I do the following in a script:

```
$ cat event_monitor.sh 
#!/bin/bash

OLD_IFS=$IFS
IFS='
'

events="Created new conference"

container=$(docker ps | grep jitsi | grep jicofo | awk '{print $NF}')
[ -z "$container" ] && { echo "ERROR: no jicofo container running yet" ; exit 1 ; }

echo "* Listening on logs from container: $container"

cat<<EOT
  docker logs -f ${container} --since 0s  2>&1 
EOT

docker logs -f ${container} --since 0s 2>&1  | \
  grep --line-buffered -E "$events" | \
  while read cur_event
  do
    IFS=$OLD_IFS
    echo "Event $(hostname): $cur_event" 
    echo "Event $(hostname): $cur_event" | /home/ops/icinga-plugins/custom/slack/slack_pipe console-wue
  done
```

//magnus

**Comment by jbg** [comment]
A Prosody plugin is a better place to do this, since Prosody already gives events for user joining MUC, user leaving MUC, etc. Just have to write a little bit of Lua:

```lua
local function joined(event)
  -- a user joined a call
end

local function left(event)
  -- a user left a call
end

module:hook("muc-occupant-joined", joined);
module:hook("muc-occupant-left", left);
```

Lua has HTTP client libraries etc already. You can look at some of the Prosody community modules for inspiration.

This approach is the basis for our webhooks at AVStack and it works well.

**Comment by maglub** [comment]
@jbg Absolutely!

My "problem" is that I am good at scripting in bash, and had a hard time finding a good place to start with Prosody plugins.

My hammer found a nail, to say. I also had the `slack_pipe` script laying around, which I would have had to implement in lua. I had a few minutes to get my hack to work...

Many excuses later. =) Thanks for pointing me in the right direction!

**Comment by vyatkin0** [comment]
Event Sync prosody plugin https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync
looks like what you need exactly.
