### ISSUE TITLE
How to add a login function when create a chat room?

### ISSUE THREAD

**Issue by kangzhe0000** [jitsi/jicofo#265]
I want to add login fucntion before create chat room.   how can I do it?

**Comment by damencho** [comment]
These are the instructions: https://github.com/jitsi/jicofo#secure-domain

**Comment by kangzhe0000** [comment]
I use the quick-install to install the jitsi server, jicofo can't run.

**Comment by kangzhe0000** [comment]
I do it as the instructions, but it doesn't work.  How can I find the problem?

**Comment by damencho** [comment]
Tell us what is the problem. Maybe attach js console logs and jicofo logs so we can take a look.

**Comment by kangzhe0000** [comment]
I configured as instructions, but there is still no login before create room.
![1](https://user-images.githubusercontent.com/22000426/37756268-d1e78ac0-2de3-11e8-919b-cb56be30d5b4.png)
![2](https://user-images.githubusercontent.com/22000426/37756272-d6216d18-2de3-11e8-858d-d377758d09fd.png)

**Comment by kangzhe0000** [comment]
am I config wrongly?

**Comment by damencho** [comment]
In prosody you should have:
```
VirtualHost "mcu.gotoai.net"
    authentication = "internal_plain"
....
VirtualHost "guest.mcu.gotoai.net"
    authentication = "anonymous"
```

In jicofo's /etc/jitsi/jicofo/sip-communicator.properties
You should have:
`org.jitsi.jicofo.auth.URL=XMPP:mcu.gotoai.net`

Is this correct in your config, cannot see this on the screen shots, the config.js looks fine.

**Comment by kangzhe0000** [comment]
Thank you！！  It's OK. I'm lack of 'org.jitsi.jicofo.auth.URL=XMPP:mcu.gotoai.net'.   
 Now login function is OK, but where the user account and password configured?   Is there a regsist function?

**Comment by kangzhe0000** [comment]
![1521797586 1](https://user-images.githubusercontent.com/22000426/37822032-4e2ece0e-2ec0-11e8-902c-23b96d2c302a.jpg)

**Comment by damencho** [comment]
Yep that is the function to create user, but you are using wrong domain. It should be mcu.gotoai.net, this is the virtual host where you enabled authentication.
