### ISSUE TITLE
How to config for multi jitsi-video-bridge instance?

### ISSUE THREAD

**Issue by nam1665** [jitsi/jicofo#270]
Dear Jitsi Team, 
I want to ask how to config for multi jitsi-video-bridge instance. 
Right now, in server 1, I already setup prosody and nginx and jicofo. 
My prosody config in server 1 is: 
_VirtualHost "domain.of.server.1"
authentication = "anonymous"
ssl = {
key = "/var/lib/prosody/domain.of.server.1.key";
certificate = "/var/lib/prosody/domain.of.server.1.crt";
}                   
modules_enabled = {
"bosh";
"pubsub";
"s2s";
}
VirtualHost "auth.domain.of.server.1"
authentication = "internal_plain"
admins = { "focus@auth.domain.of.server.1"}
Component "conference.domain.of.server.1" "muc"
Component "jitsi-videobridge.domain.of.server.1"
component_secret = "YOURSECRET1"
Component "focus.domain.of.server.1"
component_secret = "YOURSECRET2"
admins = {"domain.of.server.1","domain.of.server.2"}
allow_anonymous_s2s = true
component_ports = { 8888 }
component_interface = "ip.of.server.2"_

And in home/user/.sip-communicator/sip.comunicator.properties file, I already added these lines:

_org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false    org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=ip.of.server.1
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=pubsub
org.jitsi.videobridge.PUBSUB_SERVICE=domain.of.server.1
org.jitsi.videobridge.PUBSUB_NODE=sharedStatsNode
org.jitsi.focus.pubsub.ADDRESS=domain.of.server.1
org.jitsi.jicofo.STATS_PUBSUB_NODE=sharedStatsNode_

In server 2, I download Jitsi-video-bridge, and in home/user/.sip-communicator/sip.comunicator.properties file, I already added theses lines:
org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false  org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=ip.of.server.2
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=pubsub
org.jitsi.videobridge.PUBSUB_SERVICE=domain.of.server.1
org.jitsi.videobridge.PUBSUB_NODE=sharedStatsNode

But when I run this command in Jitsi-video-bridge  on server 2: 
_screen ./jvb.sh --hosts=domain.of.server.1 --domain=domain.of.server.1 --port=8888 --secret=YOURSECRET1_
It seems can connected to server 1, but can't get any information. The log is: 
_org.jitsi.meet.ComponentMain.call().278 java.io.EOFException: input contained no data, host:domain.of.server.1, port:8888_

In server 1, I checked the log in prosody, the component can't not be bounded. The log is: 
_jitsi-videobridge1.domain.of.server.1:component	warn
Component not connected, bouncing error for: <iq id='X01u5-819' type='get' to='jitsi-videobridge1.domain.of.server.1' from='focus@auth.domain.of.server.1/focus2936228778827373'>_

Where do I wrong, thank you so much guys, have a good coding time.

**Comment by damencho** [comment]
Please do not post your question in every possible place.
