### ISSUE TITLE
H264 with Chrome Version 66.0.3359.117 does not work

### ISSUE THREAD

**Issue by gmemon** [jitsi/jicofo#276]
I just updated my chrome version from 65 to 66 (66.0.3359.117), and all of a sudden I can no longer get the video through the videobridge. I have tried both the stable version (1030-1) and the nightly version (1053-1). But the result is the same. I am using H264. 

I noticed that H264 is advertised in jicofo's offer:
type: offer, sdp: v=0
o=- 1923518516 2 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE audio video data
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10; useinbandfec=1
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=ssrc:1027441050 cname:mixed
a=ssrc:1027441050 label:mixedlabelaudio0
a=ssrc:1027441050 msid:mixedmslabel mixedlabelaudio0
a=ssrc:1027441050 mslabel:mixedmslabel
a=rtcp-mux
m=video 1 RTP/SAVPF 107 100 101 96 99 97
c=IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:99 rtx/90000
a=rtpmap:97 rtx/90000
a=fmtp:100 x-google-start-bitrate=800
a=fmtp:107 x-google-start-bitrate=800
a=fmtp:101 x-google-start-bitrate=800
a=fmtp:96 apt=100
a=fmtp:99 apt=107
a=fmtp:97 apt=101
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=ssrc:2237654138 cname:mixed
a=ssrc:2237654138 label:mixedlabelvideo0
a=ssrc:2237654138 msid:mixedmslabel mixedlabelvideo0
a=ssrc:2237654138 mslabel:mixedmslabel
a=rtcp-mux
m=application 1 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:data
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=rtcp-mux
a=sctpmap:5000 webrtc-datachannel 1024

But chrome's response does not carry H264:

type: offer, sdp: v=0
o=- 1923518516 2 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE audio video data
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10; useinbandfec=1
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=ssrc:1027441050 cname:mixed
a=ssrc:1027441050 label:mixedlabelaudio0
a=ssrc:1027441050 msid:mixedmslabel mixedlabelaudio0
a=ssrc:1027441050 mslabel:mixedmslabel
a=rtcp-mux
m=video 1 RTP/SAVPF 107 100 101 96 99 97
c=IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:99 rtx/90000
a=rtpmap:97 rtx/90000
a=fmtp:100 x-google-start-bitrate=800
a=fmtp:107 x-google-start-bitrate=800
a=fmtp:101 x-google-start-bitrate=800
a=fmtp:96 apt=100
a=fmtp:99 apt=107
a=fmtp:97 apt=101
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X. rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=ssrc:2237654138 cname:mixed
a=ssrc:2237654138 label:mixedlabelvideo0
a=ssrc:2237654138 msid:mixedmslabel mixedlabelvideo0
a=ssrc:2237654138 mslabel:mixedmslabel
a=rtcp-mux
m=application 1 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:data
a=sendrecv
a=ice-ufrag:69cb71cbg5em7s
a=ice-pwd:1j6ubm6olv6d7mudqea374tqig
a=fingerprint:sha-1 
a=candidate:1 1 ssltcp 2130706431 X.X.X.X 8443 typ host generation 0
a=candidate:3 1 udp 2130706431 X.X.X.X 4172 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 Y.Y.Y.Y 8443 typ srflx raddr X.X.X.X rport 8443 generation 0
a=candidate:4 1 udp 1677724415 Y.Y.Y.Y 4172 typ srflx raddr X.X.X.X rport 4172 generation 0
a=rtcp-mux
a=sctpmap:5000 webrtc-datachannel 1024
Chrome 66, however, does support H264. I tried P2P mode with jicofo and chrome 66 on both ends, everything works. So it seems that jicofo is offering something to chrome 66 that it doesnt like and simply ignores. 

Can you please help me in figuring out how to solve this problem?

Thanks,
-Ghulam

**Comment by bbaldino** [comment]
I wonder if it might be related to this: https://bugs.chromium.org/p/webrtc/issues/detail?id=8808

I think as part of this change they got more strict on the packetization modes.  We should look at what a chrome offer looks like with regards to h264.  I see the Jicofo offer doesn't seem to have any of the fmtp params, maybe chrome < 65 responded to that ok but 66 doesn't?  You didn't change the Jicofo version I assume, right?

cc @gpolitis

**Comment by gmemon** [comment]
Thanks guys!! Is there a quick fix on my end that I can look into? It's a bit urgent as chrome 66 is now rolling out to public.

**Comment by gmemon** [comment]
When trying jitsi-videobridge 1053-1 from the unstable branch, I also updated the jicofo version to 1.0-403-1 from the same unstable version. When trying jitsi-videobridge 1030-1 from the stable branch I am using jicofo 1.0-394-1

**Comment by gmemon** [comment]
Hi guys, any further updates here? Would really appreciate your help!!

**Comment by bbaldino** [comment]
we'd need to add the missing fmtp params around here: https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java#L370

**Comment by gmemon** [comment]
I have added this line after line 370: addParameterExtension(h264, "profile-level-id", "42e01f;level-asymmetry-allowed=1;packetization-mode=1;), and things are working fine. Would be great if jicofo source already came with this line :)

**Comment by bbaldino** [comment]
> I have added this line after line 370: addParameterExtension(h264, "profile-level-id", "42e01f;level-asymmetry-allowed=1;packetization-mode=1;), and things are working fine. Would be great if jicofo source already came with this line :)

Open a PR and your wish can come true!
