### ISSUE TITLE
can multiple jicofo instances be running in a domain?

### ISSUE THREAD

**Issue by vincentwlau** [jitsi/jicofo#296]
I try to avoid any single point of failure in a video conferencing system using Jitsi.  So far, XMPP server, Jitsi video-bridge and Jibri can be run in multiple instances of machines. But it is not clear if a standalone Jicofo can be run concurrently on multiple machines.  Is Jicofo designed as a singleton in the system? Has anyone set up multiple Jicofo's running in one XMPP domain?  If yes, would you like to share how it is done.  If no, is there a plan to make Jicofo more fault-tolerance or fail-over capable (similar to the original goal of Openfire offocus plugin)?

**Comment by damencho** [comment]
None of the components can run in cluster like mode. 
One web, server, one xmpp server, one jicofo and multiple videobridges which are load balanced by jicofo, this setup we call a shard. 
To have a fail-over system you must run multiple shards and in front of them you can run haproxy which will route requests of one conference to the same shard, this routing is based on the fact all bosh requests has a param with the room name.
This is the way meet.jit.si is currently running with shards in different geo regions.

Please, in the future do not open issues for questions, for that you can use community.jitsi.org. When you opened the issue, didn't the template load with that information?
