### ISSUE TITLE
Can't set process on background

### ISSUE THREAD

**Issue by volga629** [jitsi/jicofo#3]
Hello Everyone,
When I am trying start focus as background process it just dies with error on file descriptor.

```
12:32:07.197 FINE: [9] plugin.reconnectplugin.ReconnectPluginActivator.start().238 Found 0 already installed providers.
12:32:07.517 SEVERE: [20] org.jitsi.jicofo.Main.run().315 java.io.IOException: Bad file descriptor
java.io.IOException: Bad file descriptor
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:272)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
    at org.jitsi.jicofo.Main$2.run(Main.java:308)
    at java.lang.Thread.run(Thread.java:745)

```

Off topic
I posting problem here, because my emails never got posted in dev mailing list. Not sure where the problem.
Here mail server log when I sent last email.

```
Dec 19 12:39:18 camailsrv01 smtp-skillsearch/smtp[1530]: E41AA427E1: to=<dev@jitsi.org>, relay=ASPMX.L.GOOGLE.COM[64.233.171.26]:25, delay=1.7, delays=0.01/0.02/0.78/0.85, dsn=2.0.0, status=sent (250 2.0.0 OK 1419010758 t5si12390172qak.118 - gsmtp)
```

**Comment by bickelj** [comment]
volga629 can you try running jicofo in a way similar to what is below?

    nohup /bin/bash /full/path/to/jicofo/dist/linux/jicofo-linux-x64-1/jicofo.sh --domain=my.example.com --secret=YOURSECRET2 --user_domain=auth.my.example.com --user_name=focus --user_password=YOURSECRET3 </dev/null >>/var/log/jitsi/jicofo.log 2>>/var/log/jitsi/jicofo.err &

Assumes you are cloning jicofo, building with ant, unzipping, have the above dirs already present, etc.

**Comment by volga629** [comment]
I tried before nohup didn't worked, because process couldn't be on background.

**Comment by bgrozev** [comment]
Outdated
