### ISSUE TITLE
may be i missing something

### ISSUE THREAD

**Issue by johnfelipe** [jitsi/jicofo#323]
![snag-0114](https://user-images.githubusercontent.com/428820/47909842-0ca1f480-de5f-11e8-92dd-5f11f84bd91b.png)

and

![snag-0115](https://user-images.githubusercontent.com/428820/47909966-64d8f680-de5f-11e8-8155-2feb164542aa.png)

and is with good domain

![snag-0116](https://user-images.githubusercontent.com/428820/47910328-84bcea00-de60-11e8-93dd-43af58e97867.png)

but i not secure my installation, pls help me

**Comment by damencho** [comment]
Have you restarted prosody? Have you added the required jicofo config and restart jicofo?

In the future please use the community forum before opening issues for your questions or problems.
