### ISSUE TITLE
Update Secure Domain

### ISSUE THREAD

**Issue by miningandhydraulics** [jitsi/jicofo#330]
You might want to update the secure domain instructions, that you need to add the additional lines to cnfig.js in /etc/jitsi/jicfo/config.js

domain: 'domain.com'
anoymousdomain: 'guest.domain.com

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening issues.

This is already the case in `2 In Jitsi Meet config.js configure 'anonymousdomain':`. And there is no such file /etc/jitsi/jicfo/config.js.
