### ISSUE TITLE
State introspection (via REST?)

### ISSUE THREAD

**Issue by paulvt** [jitsi/jicofo#38]
We are interested in retrieving the state information of Jicofo, that is, which conferences are running and who are participating (and how long).  Currently, we are trying to use the reservation system to tackle this issue by at least registering reservations, i.e. conference creations and destructions, but this is not ideal (since it works in the other direction).

Since the JVB also has a REST API (Colibri) on a lower layer, would it not be useful to have a REST API on the Jicofo level as well?

**Comment by bgrozev** [comment]
This is implemented in `/metrics` and `/debug`
