### ISSUE TITLE
Component not connected, bouncing error 

### ISSUE THREAD

**Issue by deepdad** [jitsi/jicofo#425]
## Description
callcontrol.IP.com:component	warn	Component not connected, bouncing error for: <iq id='rfJ44-29489' type='get' to='callcontrol.IP.com' from='focus@auth.counseledmeetings.com/focus41950763403501'>

This is reported in prosody.log but since it contains 'focus' I guess it is from jicofo.
I don't know whether it is causing problems because I can set up a video call between two jitsi mobile clients. It is an error though so it seems severe.

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
This is for jigasi. Ignore it.

**Comment by damencho** [comment]
And use the community forum before opening new issues.

**Comment by deepdad** [comment]
I am looking to develop jigasi
