### ISSUE TITLE
Can i record Conference info  to db?

### ISSUE THREAD

**Issue by newboy2004** [jitsi/jicofo#429]
hi,
   Can i  record  Conference  info  to db  in jicofo?

## Description
i hava a require that  record Conference info  to db in jicofo, but i do not know where i recored Conference info in  from jicofo code? please tell me tks!

## Current behavior
i expect  restful  api  for create Conference to record Conference info  to db,ok?

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

If you want to gather stats like for conferences, you can make a prosody module that sends events to a service of yours that will be saving those events to a backend of your choice. Or you can implement some kind of jicofo logs scrapping and dumping info in the backend.
