### ISSUE TITLE
Can't join a created room after Secure domain configuration

### ISSUE THREAD

**Issue by PhilippKath** [jitsi/jicofo#433]
The Secure domain readme says: 
`Whenever new room is about to be created Jitsi Meet will prompt for user name and password. After room is created others will be able to join from anonymous domain. `

My  interpretation is that only the admin can create a new room. This works for me. But i think guests should be able to join a room without the admin having to be present. Is that correct?

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

No, this is not correct, in this mode, only authenticated users will be able to create rooms and the guests can join only after the authenticated user joins.
