### ISSUE TITLE
Buildfile: build.xml does not exist!

### ISSUE THREAD

**Issue by leonidas-o** [jitsi/jicofo#434]
running on CentOS: 7

```
mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_77/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.12.1.el7.x86_64", arch: "amd64", family: "unix"
```
```
ant -version
Apache Ant(TM) version 1.9.7 compiled on April 9 2016
```

I'm updating my Jitis-Meet from time to time with an ansible playbook. I can't say what the last running version was, It was working all the time, but now I was about to update to:
- jitsi_meet_version: "jitsi-meet_4277"
- jitsi_jicofo_version: "jitsi-meet_4277"
- jitsi_videobridge_version: 1132

The last 4 tasks which are executed:
1. git clone jicofo
2. `mvn -U clean package -DskipTests`
3. `mvn dependency:get -DartifactId=maven-ant-tasks -DgroupId=org.apache.maven -Dversion=2.1.3`
4. `ant -lib ~/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar dist.lin64`

Task 4 failes with the error message: `Buildfile: build.xml does not exist!`. I saw an old thread talking about the java version. But this seems ok.
```
update-alternatives --config java

There are 2 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
 + 1           /usr/java/jdk1.8.0_77/jre/bin/java
*  2           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/bin/java)

Enter to keep the current selection[+], or type selection number: ^C
```
```
update-alternatives --config javac

There is 1 program that provides 'javac'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/java/jdk1.8.0_77/bin/javac
```

Something broken or any significant changes on the latest versions?

**Comment by damencho** [comment]
Please use the community forum when having problems or questions before opening new issues.

We had removed ant. You can use maven to create archives.
