### ISSUE TITLE
Jicofo & Shibboleth authentication leads to 404 error from Jetty

### ISSUE THREAD

**Issue by jcfischer** [jitsi/jicofo#441]
## Description
A current version of Jitsi Meet with Shibboleth authentication enabled doesn't fully finish the authentication cycle. See https://github.com/jitsi/jicofo/issues/404 where this problem was discussed. I am opening this bug report to put it back onto the tracker

## Current behavior
The redirect to the login URL (`https://intern.meet.switch.ch/login/?machineUID=775da0e27bb4432198d1142eccae8b8e&room=moep@conference.intern.meet.switch.ch&close=false`) fails with a 404 from the Jetty server in Jicofo.

## Expected Behavior
Authenticated login redirect is handled correctly by Jicofo

## Possible Solution
https://github.com/jitsi/jicofo/issues/404#issuecomment-597298433

## Steps to reproduce
Install Jitsi-meet with Shibboleth authentication. Create a conference and sign in with Shibboleth

# Environment details
```
root@jitsi-intern:~# dpkg -l | grep jit
ii  jitsi-meet-prosody                    1.0.3901-1                                      all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                        1.0.3901-1                                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.3901-1                                      all          Configuration for web serving of Jitsi Meet
root@jitsi-intern:~# dpkg -l | grep proso
ii  jitsi-meet-prosody                    1.0.3901-1                                      all          Prosody configuration for Jitsi Meet
ii  prosody                               0.11.4-1~bionic2                                amd64        Lightweight Jabber/XMPP server
```

installed via https://github.com/switch-ch/jitsi-deploy

**Comment by localguru** [comment]
I do see the same here with

```
ii  jitsi-meet                            1.0.4101-1
ii  jitsi-meet-prosody                    1.0.3729-1
ii  jitsi-meet-web                        1.0.3729-1
ii  jitsi-meet-web-config                 1.0.3729-1
ii  jitsi-videobridge                     1126-1
```

**Comment by jcfischer** [comment]
I can confirm that #446 fixes this problem for us
