### ISSUE TITLE
Regression bug for Shibboleth Authentication

### ISSUE THREAD

**Issue by SimonMaenaut** [jitsi/jicofo#446]
Setting up Jicofo with Shibboleth Authentication on Apache in the latest build we came across an error which we think might have been introduced by #408 as it sets a stringent check on the target, while we have found the target to come with a trailing forward slash at the end. This might also be partially responsible for #441 although an incorrect configuration is more likely given the limited documentation for implementing Shibboleth. This also means that #404 was only partially fixed.

**Comment by bbaldino** [comment]
Thanks for the report...if this is the case that should be an easy fix.  Are there any other URLs that we need to make sure are handled?

@damencho, maybe we can change that line to a `startsWith`-type check?

**Comment by bertvandepoel** [comment]
Simon and I worked on this together and he is in the process of submitting a PR to replace .equals with .startsWith. We've tested this many times on our setup to prevent further issues of course.

**Comment by damencho** [comment]
I wanted to fix this before we promote anything to stable :) to basically fix it for stable. So good timing @bertvandepoel
