### ISSUE TITLE
changes in java code are not reflected

### ISSUE THREAD

**Issue by nkod-pl** [jitsi/jicofo#450]
I am trying to modify java code to block muting.
in line
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java#L2289

i have changed
  boolean handleMuteRequest(Jid fromJid,
                              Jid toBeMutedJid,
                              boolean doMute)
    {
to 

  boolean handleMuteRequest(Jid fromJid,
                              Jid toBeMutedJid,
                              boolean doMute)
    {
return false;

recompiled jar, replaced in my quickinstall ubuntu installation,
but mute remote particiant  still works.
why?

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

Have you restarted jicofo?
