### ISSUE TITLE
getStress maximum is 1 resulting in incorrect stress sort at some point

### ISSUE THREAD

**Issue by Chocobozzz** [jitsi/jicofo#454]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

Octo is not enabled, but we have several video bridges in a MUC room.

## Current behavior
---

On init, `MAX_TOTAL_PACKET_RATE_PPS` is automatically set to  `50800.0`. At one point, our bridges are beyond this limit so all bridges have the stress value set to 1 (see https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/bridge/Bridge.java#L371). Then, the same bridge is always selected because you cannot sort correctly the list.

## Expected Behavior
---

Even if the `MAX_TOTAL_PACKET_RATE_PPS` limit is reached, correctly sort the bridges according to their load.

## Possible Solution
---

Either adjust `MAX_TOTAL_PACKET_RATE_PPS` using `lastReportedPacketRatePps`, or not limit the max stress value to 1 (so you can still sort the bridges).

## Steps to reproduce
---

# Environment details
---

```
ii  jitsi-videobridge2               2.1-164-gfdce823f-1         all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  jicofo                           1.0-541-1                   all          JItsi Meet COnference FOcus
```

**Comment by bgrozev** [comment]
Thanks for reporting! We'll work on a fix.
