### ISSUE TITLE
Wrong time in log report

### ISSUE THREAD

**Issue by nettunodev** [jitsi/jicofo#457]
Hello, I'm using jicofo v. 1.0-541-1 on Ubuntu 16.04. The time showed in the log file is nine hours behind the actual time. Here is an example of an entry that was written just a couple of minutes ago (actual time 2020-04-06 21:10:...)

`Jicofo 2020-04-06 12:10:30.777 INFO: [29] org.jitsi.jicofo.FocusManager.log() Disposed conference for room:`

Is there maybe something to set in some configuration file to fix this?
Thanks

**Comment by mymedia2** [comment]
What time zone is the server in?

**Comment by nettunodev** [comment]
> What time zone is the server in?

Europe / Rome
