### ISSUE TITLE
Regression: health check always fails in jicofo 1.0-549: No MUC service found on XMPP domain or Jicofo has not finished initial components discovery yet

### ISSUE THREAD

**Issue by agusdallalba** [jitsi/jicofo#472]
## Description
I've upgraded my Ubuntu jitsi-meet server to the version published today and now I get the following error in the log every 10 seconds:
```
Jicofo 2020-04-17 20:54:45.270 SEVERE: [32] org.jitsi.jicofo.health.Health.log() No MUC service found on XMPP domain or Jicofo has not finished initial components discovery yet
Jicofo 2020-04-17 20:54:45.270 SEVERE: [32] org.jitsi.jicofo.health.Health.log() Health check failed in PT0.000423S:
java.lang.RuntimeException: No MUC component
	at org.jitsi.jicofo.health.Health.check(Health.java:114)
	at org.jitsi.jicofo.health.Health.performCheck(Health.java:88)
	at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
Jicofo 2020-04-17 20:54:55.270 SEVERE: [32] org.jitsi.jicofo.health.Health.log() No MUC service found on XMPP domain or Jicofo has not finished initial components discovery yet
```
I attached the full log as [jicofo.log](https://github.com/jitsi/jicofo/files/4495742/jicofo.log)

**The error is benign**, the server appears to function normally despite the failed health checks. 

**Downgrading with `dpkg -i jicofo_1.0-544-1_all.deb` fixes the problem.**

# Environment details
- Ubuntu 18.04 on a small 1 core 1 GB RAM VPS.
- `jicofo/stable 1.0-549-1 all` from `https://download.jitsi.org stable/`
- `jitsi-meet/stable 2.0.4468-1 all` from `https://download.jitsi.org stable/`
- `jitsi-meet-prosody/stable 1.0.4025-1 all` from `https://download.jitsi.org stable/`
- `jitsi-meet-web/stable 1.0.4025-1 all` from `https://download.jitsi.org stable/`
- `jitsi-meet-web-config/stable 1.0.4025-1 all` from `https://download.jitsi.org stable/`
- `jitsi-videobridge2/stable 2.1-183-gdbddd169-1 all` from `https://download.jitsi.org stable/`
- `openjdk-13-jre-headless/bionic 13.0.1+9-2~18.04 amd64` from `http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic main`
- `prosody 0.11.5-1~bionic6 amd64` from `https://packages.prosody.im/debian bionic main`
- Octo with MUCs and RegionBasedBridgeSelectionStrategy.

**Comment by bgrozev** [comment]
Thanks for the report. We recently changed to health checks running in the background (as opposed to on-demand when we receive an HTTP request), which must be what surfaced this.

I don't understand how things work correctly despite this error, I'll look into it further.

**Comment by bgrozev** [comment]
Have you configured prosody to not report its version? I still don't understand why this happens, but [this change](https://github.com/jitsi/jicofo/pull/476) will either fix it or add a more useful message.

**Comment by agusdallalba** [comment]
Indeed I had the version module commented out in `prosody.cfg.lua`. I uncommented it and now the health checks work again.

Would you like me to test with the master branch?

**Comment by bgrozev** [comment]
No, that's not necessary. Tip of master should work with the version disable module, too.
