### ISSUE TITLE
Secure domain: No connection with Jitsi Meet on Android

### ISSUE THREAD

**Issue by dschmidtke** [jitsi/jicofo#482]
## Description
---
Installed jitsy-meet on Debian 10 from the official repository download.jitsy.org on my vserver (PHP-FPM 7.3, Apache 2.4). Tried several Jitsi Meet clients (IOS, Android, Browser). Everything worked as expected.

Next I configured authentification according to the docs at https://github.com/jitsi/jicofo#secure-domain. The result was that it was impossible to create or join an existing conference on Android -- while IOS app and browser worked as expected.

## Current behavior
---
Installed Jitsi Meet on my Android device. Configured my server url in settings. 

Entered the name of a non-existing conference and tapped "join". A message appears: disconnected and retry in x seconds. And so on.

Started a conference with a new name in another client. Back on Android I entered the same new name and tapped join. Same message appears as before. Disconnected. Retry. And so on.    

## Expected Behavior
---
Android App flow should be the same like IOS app or in the browser: When entering the name of a non-existing conference, prompt the participant to wait for the organiser or enter credentials.

When entering the name of an existing conference, let the participant enter the room.

# Environment details
---
Tried with the current Android app 20.2.0 from f-droid. I asked someone else to install the App from Google Play - same problems. Again: it works for me on IOS and in the browser.

**Comment by bgrozev** [comment]
Use community.jitsi.org if this is still not resolved
