### ISSUE TITLE
Jicofo 1.0-566-1 uses 100% CPU even when no conference is running

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [jitsi/jicofo#501]
## Description
After the update to Jicofo 1.0-566-1 (and restart of the services) the `jicofo` services always uses 100% CPU. Even when there is no conference running.

Video conferences are still working.

---

## Current behavior
After the update to Jicofo 1.0-566-1 (and restart of the services) the jicofo services always uses 100% CPU. Even when there is no conference running.
(see https://community.jitsi.org/t/jicofo-maxes-out-one-core-after-latest-update-with-no-conferences-running/48736/7)

```
root@debian9164m ~ # top -b -n 5 -d 2 -u jicofo 
top - 11:58:16 up  1:15,  6 users,  load average: 1.63, 1.83, 2.12
Tasks: 745 total,   1 running, 744 sleeping,   0 stopped,   0 zombie
%Cpu(s): 14.9 us,  2.0 sy,  0.0 ni, 76.4 id,  6.8 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  64254.9 total,  43055.2 free,  10826.8 used,  10372.8 buff/cache
MiB Swap:  32736.0 total,  32736.0 free,      0.0 used.  52383.8 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
26241 jicofo    20   0 9057516 215652  28268 S  94.4   0.3   2:15.81 java
26241 jicofo    20   0 9057516 215652  28268 S 100.0   0.3   2:17.82 java
26241 jicofo    20   0 9057516 215652  28268 S 100.5   0.3   2:19.84 java
26241 jicofo    20   0 9058544 215652  28268 S 100.0   0.3   2:21.85 java
26241 jicofo    20   0 9058544 215652  28268 S 100.5   0.3   2:23.87 java
```

Logged messagess with a severity > INFO:

```
root@debian9164m ~ # grep -v INFO /var/log/jitsi/jicofo.log 

Jicofo 2020-05-01 12:16:18.062 WARNING: [14] org.jitsi.jicofo.FocusManager.log() No dedicated JVB MUC XMPP connection configured - falling back to the default XMPP connection
Jicofo 2020-05-01 12:16:18.655 SEVERE: [21] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for focus.jitsi.ypbind.de: XMPP error reply received from focus.jitsi.ypbind.de: XMPPError: service-unavailable - wait
Jicofo 2020-05-01 12:16:18.663 SEVERE: [21] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for speakerstats.jitsi.ypbind.de: XMPP error reply received from speakerstats.jitsi.ypbind.de: XMPPError: service-unavailable - cancel
Jicofo 2020-05-01 12:16:18.665 SEVERE: [21] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for conferenceduration.jitsi.ypbind.de: XMPP error reply received from conferenceduration.jitsi.ypbind.de: XMPPError: service-unavailable - cancel
Jicofo 2020-05-01 12:16:23.379 WARNING: [33] org.jitsi.jicofo.bridge.BridgeSelector.log() No pub-sub node mapped for jvbbrewery@internal.auth.jitsi.ypbind.de/618520c8-9eb1-4a3e-b96a-fa61983cf73b
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/usr/share/jicofo/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

(**Note**: According to #490 the XMPP errors can be ignored).

---

## Expected Behavior
Jicofo service should behave normal and don't hog a single CPU while idling.

---

## Possible Solution
None at the moment.

*Workaround:* Downgrade jicofo to the previous version 1.0-549 will resolve this issue.

---

## Steps to reproduce
Install / Upgrade Jicofo 1.0-566-1 and restart `jicofo.service`

---

# Environment details
OS: Debian GNU/Linux 10 (buster), latest packages as of may 1st, 2020.
CPU: 8xIntel(R) Core(TM) i7-6700 CPU @ 3.40GHz
RAM: 64 GB
Running on a bare metal server (no docker/podman/lxc ...)

Java version is:

```
root@debian9164m ~ # java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)
```

---

**Comment by JonathanLennox** [comment]
Should be fixed by https://github.com/jitsi/jicofo/pull/502 .

**Comment by ashirwad007786** [comment]
@JonathanLennox When this change will be live on Debian package(quick install)?

**Comment by JonathanLennox** [comment]
@damencho is working on this; I believe he's hoping to get it out today.

**Comment by ashirwad007786** [comment]
@JonathanLennox Sure, thank you. Please let us know here when it's out so that we can update this on our server.

**Comment by damencho** [comment]
We pushed an update to stable which is jicofo 567.

**Comment by colarocker** [comment]
awesome, works good for me on ubuntu 20.04, thanks for the fast update <3

**Comment by Bobobo-bo-Bo-bobo** [comment]
Damn! You are fast!
The update fixes this issue. Thank you very much!

**Comment by ashirwad007786** [comment]
@damencho I purged and again installed using quick install. Still, I'm getting 100% CPU on 1 core.

**Comment by damencho** [comment]
Have you checked the jicofo version? Is it 566 or 567?

**Comment by edvinkuric** [comment]
Hello,
i still have the same issue with the CPU Utilization only when building the jar-file myself from the current master-branch.
When using the remote-package of jicofo instead of selfbuilt jicofo.jar, then this behaviour is fixed.

Any idea what could be causing this?

i built the jar-package with "mvn package -DskipTests" and replaced that with the original jicofo.jar in /usr/share/jicofo
