### ISSUE TITLE
Don't expose password in process listing

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [jitsi/jicofo#504]
## Description
The service will use the authentication password as a command line option (`--user_password=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Current behavior
The service will use the authentication password as a command line option (`--user_password=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Possible Solution
I haven't touched Java for years, but if I'm recalling correctly the command line arguments  are not immutable in Java (they aren't in C/Go/Rust).

Unlike "classic" UNIX systems the process arguments on Linux are not read only. Changing the relevant argument to some obfuscated value (after processing them) will be reflected in the process output of the operating system.

This can be used to prevent access to the password/shared secrets to anyone running `ps`.

**Comment by mymedia2** [comment]
The obfuscating still leaves a possibility to win a race condition while service startup and to see a password.

**Comment by obfusk** [comment]
> The obfuscating still leaves a possibility to win a race condition while service startup and to see a password.

Indeed. I suggest using an environment variable or configuration file to pass the password to the java process instead.

**Comment by Bobobo-bo-Bo-bobo** [comment]
@mymedia2 You are right there is a race condition during the service start, but at least the time of exposure is limited

@obfusk This is the alternative and I think the best solution. The configuration is actually stored in `/etc/jitsi/jicofo/config` (at least on Debian) so simply parsing that file or sourcing and exporting the variables could be an option to avoid breaking existing installations.

**Comment by obfusk** [comment]
Since the (debian) `init.d` file that starts jicofo already sets `--user_password` using `$JICOFO_AUTH_PASSWORD` from that configuration file, I'd suggest exporting those environment variables instead; and having the java code that currently processes the `--user_password` etc. command line arguments also check for `JICOFO_*` environment variables as a fallback/default.

I haven't written any Java code in a while either, but I could probably make a PR for that.
