### ISSUE TITLE
Reservations issue

### ISSUE THREAD

**Issue by techmagician** [jitsi/jicofo#511]
In the stable version from last week, I configured the reservation system by adding:
org.jitsi.impl.reservation.rest.BASE_URL=http://reservation.example.com

into the file:
/etc/jitsi/jicofo/sip-communicator.properties

That server is working as expected. The reservation request gets sent to my reservation server, and it works as expected.

I created a new server from scratch yesterday (I noticed you promoted a new version as the stable release.)

As soon as I added the same setting, the server stopped working for more than 3 participants. The participants can see that there are 3 participants, but no video is being broadcast to any client (2 participants in p2p mode continues to work properly.)

If I remove the property from the sip-communicator.properties file, and restart jicofo, after the participants re-join the room, the system works properly.

Could you please advise, is there a new way to configure reservations?
Thanks in advance!

**Comment by damencho** [comment]
Latest stable jicofo is 567, which was the previous one you used?

**Comment by techmagician** [comment]
549

**Comment by damencho** [comment]
Hum, I don't see anything suspicious in jicofo commits for that ... so I suspect this is a client issue ...

**Comment by techmagician** [comment]
Do you have any suggestions? Is there anything else I can provide to help resolve this issue?

**Comment by damencho** [comment]
As a start provide the clients js console logs and also the jicofo logs for that session. 
You can send it to damencho at jitsi dot org.

**Comment by bgrozev** [comment]
The reservation system has been moved to a prosody plugin.
