### ISSUE TITLE
jicofo REST port 8888

### ISSUE THREAD

**Issue by thomas955** [jitsi/jicofo#533]
Hi,

is this port configurable? 
I don't think so, but it would be nice. I need the port for the harvester (Dont ask .... policy things). Are there any plans or possibilities to change the port?

Thank you in advance.

**Comment by bgrozev** [comment]
You can set `org.jitsi.jicofo.auth.jetty.port=PORT` in `/etc/jitsi/jicofo/sip-communicator.properties`

**Comment by bgrozev** [comment]
For reference, the modern way would be to set `jicofo.rest.port` in `/etc/jitsi/jicofo/jicofo.conf`.

**Comment by liangguohao66** [comment]
> For reference, the modern way would be to set `jicofo.rest.port` in `/etc/jitsi/jicofo/jicofo.conf`.
why there is NO  response when request jico by rest port ? 
curl http://127.0.0.1:8888/colibri/health
