### ISSUE TITLE
There should be an easy way to modify memory settings

### ISSUE THREAD

**Issue by sanvila** [jitsi/jicofo#550]
Currently, memory setting is hardcoded in `/usr/share/jicofo/jicofo.sh` and it's not practical to modify because the changes are lost on upgrades.

Ideally, there should be a way to change that easily by modifying some file in `/etc`

This could be done in this way:

Make `jicofo.sh` read `/etc/jitsi/jicofo/config`
Add something like `JICOFO_MEMORY=-Xmx3072m` to the file in postinst the first time
and ensure also that there is a line with such variable on upgrades.
In `jicofo.sh`, drop `-Xmx3072m` and use `$JICOFO_MEMORY` instead.

As in the videobridge case, people would see the variable in the config file and immediately will know how to change the memory setting, without the need to write extra documentation.

**Comment by damencho** [comment]
This is already the case: https://github.com/jitsi/jicofo/pull/540

**Comment by damencho** [comment]
> Add something like `JICOFO_MEMORY=-Xmx3072m` to the file in postinst the first time
> and ensure also that there is a line with such variable on upgrades.
> In `jicofo.sh`, drop `-Xmx3072m` and use `$JICOFO_MEMORY` instead.

**Comment by damencho** [comment]
Sorry I didn't read it till the end :)

**Comment by bgrozev** [comment]
We've added `JICOFO_MAX_MEMORY` somewhere along the way :)
