### ISSUE TITLE
org.jitsi.jicofo.HEALTH_CHECK_INTERVAL - not respected

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jicofo#558]
## Steps
Set in `/etc/jitsi/jicofo/sip-communicator.properties` the config `org.jitsi.jicofo.HEALTH_CHECK_INTERVAL=120`

## Current behavior
[Every 10 seconds](https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java#L77) the log is spammed with:
```
INFO: [63] org.jitsi.jicofo.health.Health.log() Performed a successful health check in PT0.033579S. Sticky failure: false`
WARNING: [31] org.jivesoftware.smackx.muc.MultiUserChat.processStanza() Presence not from a full JID: __jicofo-health-check-XXXXXXXXXX@conference.meet.domain.tld
WARNING: [31] org.jivesoftware.smackx.muc.MultiUserChat.processStanza() Presence not from a full JID: __jicofo-health-check-XXXXXXXXXX@conference.meet.domain.tld
WARNING: [31] org.jivesoftware.smackx.muc.MultiUserChat.processStanza() Presence not from a full JID: __jicofo-health-check-XXXXXXXXXX@conference.meet.domain.tld
```

## Expected Behavior
Do a health check as setup, every 120 seconds.

# Environment details
Debian Buster, arm64

**Comment by bgrozev** [comment]
`org.jitsi.jicofo.HEALTH_CHECK_INTERVAL` controls the interval at which Jicofo checks the health of the bridges connected to it. The interval of the internal health checks that jicofo performs (which log the message you quote) is not configurable (and defaults to 10 seconds when enabled). Contributions for a new property to configure it are welcome.

**Comment by licaon-kter** [comment]
Ok, I've disabled the check for now.
I was more interested in the bridge discovery and that seems to work without the health check.
