### ISSUE TITLE
Every JWT authenticated user is being set as moderator in jicofo

### ISSUE THREAD

**Issue by LohithBlaze** [jitsi/jicofo#576]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Every JWT token authenticated user is being set as moderator in jicofo,  only the user who creates the room should be made as moderator.

## Current behavior
Every authenticated user with JWT is set as moderator

## Expected Behavior
Only the user with JWT should be made as moderator

## Possible Solution
Dont know

## Steps to reproduce
1. Create a random room
2. Let one user  join with JWT token and start the meeting
3. New user joins the conference, with jwt token, he is made as moderator as well.

# Environment details
Prosody 0.11.5

**Comment by damencho** [comment]
This is how it is supposed to work.

**Comment by ha3** [comment]
Hello @damencho,

Is there a way to workaround to this? We have a requirement where each participant should participate the conference via jwt tokens but only some with custom claim should be moderators.

Thank you.

**Comment by damencho** [comment]
You can disable in jicofo auto_owner and manage the moderator rights based on a jwt token field value. For inspiration look at how this module sets everybody to moderators: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_allowners.lua
