### ISSUE TITLE
Stuck: Jicofo build from package 

### ISSUE THREAD

**Issue by DhruvAwasthi** [jitsi/jicofo#580]
## Description
---
I am following the manual installation [guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual). So far I have configured the prosody, nginx, and jitsi-videobridge. Each component is working absolutely fine adn I know there is no mistake till so far.
But problem arises when I try to build jicofo from source.
![2020-08-18-224454_1366x768_scrot](https://user-images.githubusercontent.com/66522260/90548990-7235b100-e1ab-11ea-8bdd-b53560695318.png)
The steps I followed to build this are:
```
git clone https://github.com/jitsi/jicofo.git
cd jicofo
mvn package -DskipTests -Dassembly.skipAssembly=false
unzip target/jicofo-1.1-SNAPSHOT-archive.zip
cd jicofo-1.1-SNAPSHOT-archive
./jicofo.sh --host=localhost --domain=164.52.194.78 --secret=focus_secret --user_domain=auth.164.52.194.78 --user_name=focus --user_password=focuspassword

```
## Current behavior
---
When I run the last executed command, it outputs some intermediary messages for 5 seconds and then gets stuck there. No matter how long I wait, it is still there. 

## Expected Behavior
---
I'd expect a perfect install of jicofo.

## Possible Solution
---
Difficult for me to come with a solution.
## Steps to reproduce
---
```
git clone https://github.com/jitsi/jicofo.git
cd jicofo
mvn package -DskipTests -Dassembly.skipAssembly=false
unzip target/jicofo-1.1-SNAPSHOT-archive.zip
cd jicofo-1.1-SNAPSHOT-archive
./jicofo.sh --host=localhost --domain=164.52.194.78 --secret=focus_secret --user_domain=auth.164.52.194.78 --user_name=focus --user_password=focuspassword
```

# Environment details
---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID_LIKE=debian

**Comment by bgrozev** [comment]
Please discuss on community.jitsi.org or reopen if necessary
