### ISSUE TITLE
ColibriThreadingTest failure on IBM Power Linux (ppc64le) platform

### ISSUE THREAD

**Issue by seth-priya** [jitsi/jicofo#581]
## Description
mvn install -Dassembly.skipAssembly=false fails with
````
[ERROR] Failures:
[ERROR]   ColibriThreadingTest.testColibriMultiThreading:160 Endpoints that have failed to send their request: [peer0, peer2, peer3, peer4, peer5, peer6, peer7, peer8, peer9, peer10, peer11, peer12, peer13, peer14, peer15, peer16, peer17, peer18, peer19]
[ERROR] Errors:
[ERROR]   AdvertiseSSRCsTest.testDuplicatedSSRCs:248 » Runtime User1 - wait for invite t...
[ERROR]   AdvertiseSSRCsTest.testOneToOneConference:96 » Runtime User1 - wait for invite...
[ERROR]   AdvertiseSSRCsTest.testSSRCLimit:336 » Runtime User1 - wait for invite timeout
[ERROR]   AdvertiseSSRCsTest.testSourceRemoval:183 » Runtime User1 - wait for invite tim...
[ERROR]   BundleTest.testBundle:97 » Runtime user1 - wait for invite timeout
[ERROR]   ColibriTest.testChannelAllocation:110 » Timeout Timed out waiting for a respon...
[ERROR]   LeakingRoomsTest.testOneToOneConference:102 » Runtime User2 - wait for invite ...
[ERROR]   RolesTest.testPassModeratorRole:90 » Runtime User0 - wait for invite timeout
[ERROR]   ShutdownTest.setUp:84 » Runtime C1U1 - wait for invite timeout
[ERROR]   ShutdownTest.setUp:84 » Runtime C1U1 - wait for invite timeout
[ERROR]   ShutdownTest.setUp:84 » Runtime C1U1 - wait for invite timeout
[ERROR]   ShutdownTest.setUp:84 » Runtime C1U1 - wait for invite timeout
[INFO]
[ERROR] Tests run: 87, Failures: 1, Errors: 12, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:32 min
[INFO] Finished at: 2020-08-21T05:09:32-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jicofo: There are test failures.
````

## Current behavior
Failure of ColibriThreadingTest.testColibriMultiThreading on top-of-tree

## Expected Behavior
mvn install -Dassembly.skipAssembly=false should pass

## Possible Solution
Debugging in progress

## Steps to reproduce
git clone https://github.com/jitsi/jicofo ; cd jicofo ; mvn install -Dassembly.skipAssembly=false

# Environment details
Linux p006n04 3.10.0-1127.18.2.el7.ppc64le #1 SMP Mon Jul 20 22:39:41 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Comment by seth-priya** [comment]
@bbaldino thanks a lot for looking into this and providing your feedback, the tests are still failing for me with this change. This maybe something in my environment or specific to the architecture? The tests pass for me on Intel, any thoughts on debugging it?

**Comment by bbaldino** [comment]
That's strange, can you make sure you've fully cleaned everything (`mvn clean`) before you re-test?  If so, I don't know offhand what would cause the failure, you'll have to dig into it I think.

**Comment by seth-priya** [comment]
so this seems to be causing the issues

SCTP JNI load: Linux OS detected
Exception in thread "Smack-Single Threaded Executor 0 (4)" java.lang.UnsatisfiedLinkError: /tmp/nativeutils624151876038372/libjnisctp.so: /tmp/nativeutils624151876038372/libjnisctp.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a Power PC 64 LE-bit platform)

I am trying to track down the point from which this is fetched / installed and how to handle it

**Comment by bbaldino** [comment]
> so this seems to be causing the issues
> 
> SCTP JNI load: Linux OS detected
> Exception in thread "Smack-Single Threaded Executor 0 (4)" java.lang.UnsatisfiedLinkError: /tmp/nativeutils624151876038372/libjnisctp.so: /tmp/nativeutils624151876038372/libjnisctp.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a Power PC 64 LE-bit platform)
> 
> I am trying to track down the point from which this is fetched / installed and how to handle it

Ah, nice find, yeah this would do it.  We don't have access to all platforms, so we only have the native lib for jitsi-sctp for some of them.  You'd have to do a build of the jitsi-sctp lib for your platform and open a PR for it.

**Comment by seth-priya** [comment]
thank! will work on it

**Comment by bbaldino** [comment]
Depending on what you're looking to do, you could also look at disabling SCTP entirely in your deployment (we don't use it anymore and use websockets instead for that channel).  That would skip the need for compiling the native lib.

**Comment by seth-priya** [comment]
thanks @bbaldino - so, yes the first attempt to jitsi-sctp fails for me, I will look at both approaches

**Comment by imamol** [comment]
hi @bbaldino, I was able to build jitsi-sctp (on ppc64le). That created **libjnisctp-linux-ppc64le.so**  and packaged jitsi-sctip in **jniwrapper-native-1.0-SNAPSHOT.jar**. For Jicofo build, tried placing `libjnisctp-linux-ppc64le.so` in `/usr/local/lib` (where libusrsctp.so resides), but getting the same error as above. Any pointers on how to use jitsi-sctp snapshot for jicofo build? 
Thanks!

**Comment by bbaldino** [comment]
> hi @bbaldino, I was able to build jitsi-sctp (on ppc64le). That created **libjnisctp-linux-ppc64le.so** and packaged jitsi-sctip in **jniwrapper-native-1.0-SNAPSHOT.jar**. For Jicofo build, tried placing `libjnisctp-linux-ppc64le.so` in `/usr/local/lib` (where libusrsctp.so resides), but getting the same error as above. Any pointers on how to use jitsi-sctp snapshot for jicofo build?
> Thanks!

I'm confused, it's not Jicofo which needs jitsi-sctp, it's jvb.  Also, have you looked into migrating to websockets instead?  I would highly recommend that.  We plan on removing support for SCTP eventually.

**Comment by imamol** [comment]
Thanks! I haven't looked at websockets part yet, will check that out too. For now, I'll build jvb and check if that resolves the issue.

**Comment by asellappen** [comment]
is there any fix for this issue? . i am seeing the same issue on ppc64le for building package jitsi-sctp


  testSctpJni(SctpJniTest): /tmp/nativeutils11328613016570797/libjnisctp.so: /tmp/nativeutils11328613016570797/libjnisctp.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a Power PC 64 LE-bit platform)

**Comment by bgrozev** [comment]
#729 should fix the issue with running jicofo's unit tests on platforms that jitsi-sctp doesn't support.
