### ISSUE TITLE
Stress value is calculated wrong and thus bridges get overstressed

### ISSUE THREAD

**Issue by awlx** [jitsi/jicofo#615]
## Description
From time to time jicofo seems to net get the stress stats in a correct way anymore. Even tho the stress value is over 1 jicofo still reports 0,05 for this particular bridge:
```
Jicofo 2020-11-02 20:47:57.760 INFO: [9316] org.jitsi.jicofo.AbstractChannelAllocator.log() Using jvbbrewery@internal.auth.meet.ffmuc.net/jvb1.meet.ffmuc.net to allocate channels for: Participant[uni1@conference.meet.ffmuc.net/79da64c7]@1018193005
Jicofo 2020-11-02 20:47:57.920 INFO: [30] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Expiring channels for: ff_tengling@conference.meet.ffmuc.net/c1e74c75 on: Bridge[jid=jvbbrewery@internal.auth.meet.ffmuc.net/jvb1.meet.ffmuc.net, relayId=10.111.0.2:4096, region=ffmuc-de1, stress=0.07]
Jicofo 2020-11-02 20:47:59.381 INFO: [30] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Expiring channels for: ff_tengling@conference.meet.ffmuc.net/38723b36 on: Bridge[jid=jvbbrewery@internal.auth.meet.ffmuc.net/jvb1.meet.ffmuc.net, relayId=10.111.0.2:4096, region=ffmuc-de1, stress=0.07]
Jicofo 2020-11-02 20:47:59.482 INFO: [30] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Expiring channels for: triplelima@conference.meet.ffmuc.net/65fdf688 on: Bridge[jid=jvbbrewery@internal.auth.meet.ffmuc.net/jvb1.meet.ffmuc.net, relayId=10.111.0.2:4096, region=ffmuc-de1, stress=0.07]

```
## Current behavior
Bridge gets overloaded because of wrong stress values. It seems to happen only after a few days.
![Screenshot 2020-11-02 at 20 47 27](https://user-images.githubusercontent.com/6527744/97912262-db5da700-1d4c-11eb-8b8a-76deb4cc6b15.png)
![Screenshot 2020-11-02 at 20 47 20](https://user-images.githubusercontent.com/6527744/97912270-de589780-1d4c-11eb-800f-7fdeb7948f35.png)

Also Octo does not start because the stress is not seen as critical.

## Expected Behavior
Get the correct stress values and don't over stress certain bridges.

# Environment details
jvb0.meet.ffmuc.net:~# dpkg -l | grep jico
ii  jicofo                          1.0-644-1                    all          JItsi Meet COnference FOcus
ii  jitsi-videobridge2            2.1-376-g9f12bfe2-1          all          WebRTC compatible Selective Forwarding Unit (SFU)

Thanks for the help!

**Comment by JonathanLennox** [comment]
This problem was actually in jitsi-videobridge, rather than jicofo - there were cases where its task that sends status updates to jicofo would get stuck, which were fixed in https://github.com/jitsi/jitsi-videobridge/pull/1493 and https://github.com/jitsi/jitsi-videobridge/pull/1501.

Can you test with videobridge 2.1-382 or later, and see if you still see the problem?

**Comment by awlx** [comment]
Will try. Thank you for the hint!

**Comment by awlx** [comment]
It really fixed the issue. Thank you!
