### ISSUE TITLE
Moderated rooms configuration not working with Jitsi

### ISSUE THREAD

**Issue by LohithBlaze** [jitsi/jicofo#657]
## Description
I'm looking for moderated room functionality where all guest users joining are joined as visitors and only moderator can allow them to chat or speak in the room. There is a prosody config that allows this functionality named "muc_room_default_moderated" when set to true allows users to be given visitor role. When I added that config, nothing is changed and jicofo is assigning member role to all the guest users who join in the room. Do you know about this and what does it take to implement moderated rooms kind of functionality in jicofo ?

## Current behavior
When I enable the muc_room_default_moderated = true, all the users who are joining the call can speak and unmute themselves.

## Expected Behavior
Users joining the call should not be able to speak or talk unless allowed by moderator.

## Possible Solution
Enabling the muc_room_default_moderated = true was supposed to work but the functionality is not implemented from jicofo side.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues, thank you.

We are working on a similar moderation feature https://github.com/jitsi/jitsi-meet/pull/7779, it needs changes in jitsi-meet, lib-jitsi-meet and jicofo, but it is not using `muc_room_default_moderated` as such a feature needs more signaling than just setting a participant role.
