### ISSUE TITLE
can´t connect to Prosody (not-authorized, host:localhost, port:5347)

### ISSUE THREAD

**Issue by JPRuehmann** [jitsi/jicofo#663]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- Jicofo can´t connect to Prosody (not-authorized, host:localhost, port:5347)

## Current behavior
--- errormessages in the log (Mainly)
    not-authorized, host:localhost, port:5347
and unable to find valid certification path to requested target

## Expected Behavior
--- much less errors and working conferences.

## Possible Solution
--- login without certificates

## Steps to reproduce
--- start jicofo (sudo services jicofo restart)
    show error messages with  (cat /var/log/jitsi/jicofo.log | grep 'SCHWERWIEGEND')  

# Environment details
--- Kubuntu 18.04 (LTS) (32Bit)
     Java 9 bzw (8)
     ProsodyProsody 0.10.0

# Prosody directories
Data directory:     /var/lib/prosody
Config directory:   /etc/prosody
Source directory:   /usr/lib/prosody
Plugin directories:
  /usr/share/jitsi-meet/prosody-plugins/
  /usr/lib/prosody/modules/
  

# Lua environment
Lua version:                    Lua 5.1

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/local/share/lua/5.1/?.lua
  /usr/local/share/lua/5.1/?/init.lua
  /usr/local/lib/lua/5.1/?.lua
  /usr/local/lib/lua/5.1/?/init.lua
  /usr/share/lua/5.1/?.lua
  /usr/share/lua/5.1/?/init.lua
  /home/ruehmann/.luarocks/share/lua/5.1/?.lua
  /home/ruehmann/.luarocks/share/lua/5.1/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/local/lib/lua/5.1/?.so
  /usr/lib/i386-linux-gnu/lua/5.1/?.so
  /usr/lib/lua/5.1/?.so
  /usr/local/lib/lua/5.1/loadall.so
  /home/ruehmann/.luarocks/lib/lua/5.1/?.so

LuaRocks:               Installed (2.4.2)

# Lua module versions
lfs:            LuaFileSystem 1.6.3
libevent:       2.1.8-stable
luaevent:       0.4.4
lxp:            LuaExpat 1.3.0
socket:         LuaSocket 3.0-rc1
ssl:            0.6

jicofo1.0-691-1

**Comment by JPRuehmann** [comment]
How can I find out which cacerts file Jicofo is using to get its Certificate?

**Comment by JPRuehmann** [comment]
Still can´t login.

Jicofo 2021-01-13 09:40:44.714 SCHWERWIEGEND: [19] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping
Jicofo 2021-01-13 09:40:44.771 SCHWERWIEGEND: [22] org.jitsi.jicofo.xmpp.FocusComponent.log() java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused), host:localhost, port:5347

jicofo version 1.0-695-1

**Comment by JPRuehmann** [comment]
Disabled sip-communication.propperties

Now it says

```
Jicofo 2021-01-13 20:46:00.439 SCHWERWIEGEND: [22] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jicofo 2021-01-13 20:46:04.942 SCHWERWIEGEND: [20] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping
Jicofo 2021-01-13 20:46:04.978 SCHWERWIEGEND: [25] org.jitsi.jicofo.xmpp.FocusComponent.log() java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused), host:localhost, port:5347
```

**Comment by bgrozev** [comment]
These all seem like configuration issues.

`(Connection refused), host:localhost, port:5347` means that prosody is not listening on localhost:5437 as it should be.

Jicofo uses the java store for ca certs. You can completely [disable certificate verification in jicofo.conf](https://github.com/jitsi/jicofo/blob/master/src/main/resources/reference.conf#L251).

**Comment by JPRuehmann** [comment]
The videobridge can connect and uses the same Port and address (localhost 5347)

Which java keystore? System (/etc/ssl/java/cacerts) default java (/opt/java/32/jdk-9/lib/security/cacerts) or the java which is used to execute jicofo (/opt/java/32/jdk1.8.0_181/jre/lib/security/cacets)?

Without certificate:
Jicofo 2021-01-13 09:40:44.714 SCHWERWIEGEND: [19] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping
Jicofo 2021-01-13 09:40:44.771 SCHWERWIEGEND: [22] org.jitsi.jicofo.xmpp.FocusComponent.log() java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused), host:localhost, port:5347

With Certicate:
```
Jicofo 2021-01-13 20:46:00.439 SCHWERWIEGEND: [22] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jicofo 2021-01-13 20:46:04.942 SCHWERWIEGEND: [20] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping
Jicofo 2021-01-13 20:46:04.978 SCHWERWIEGEND: [25] org.jitsi.jicofo.xmpp.FocusComponent.log() java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused), host:localhost, port:5347
```
Firewall: `sudo iptables -L -n`
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-sshd   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-sshd (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0      
```
Ports: `sudo nmap -sT -p- localhost`
```
Starting Nmap 7.60 ( https://nmap.org ) at 2021-01-14 10:53 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000075s latency).
Not shown: 65506 closed ports
PORT      STATE SERVICE
21/tcp    open  ftp
22/tcp    open  ssh
25/tcp    open  smtp
53/tcp    open  domain
80/tcp    open  http
111/tcp   open  rpcbind
139/tcp   open  netbios-ssn
443/tcp   open  https
445/tcp   open  microsoft-ds
538/tcp   open  gdomap
631/tcp   open  ipp
789/tcp   open  unknown
1716/tcp  open  xmsg
2628/tcp  open  dict
2947/tcp  open  gpsd
3306/tcp  open  mysql
5154/tcp  open  bzflag
5222/tcp  open  xmpp-client
5269/tcp  open  xmpp-server
5280/tcp  open  xmpp-bosh
5939/tcp  open  unknown
6379/tcp  open  redis
6502/tcp  open  netop-rc
8000/tcp  open  http-alt
8080/tcp  open  http-proxy
8123/tcp  open  polipo
8888/tcp  open  sun-answerbook
9090/tcp  open  zeus-admin
64738/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 2.11 seconds
```
Ok, Port seems tot to be opened, but why?
Thanks,

**Comment by bgrozev** [comment]
> Which java keystore? System (/etc/ssl/java/cacerts) default java (/opt/java/32/jdk-9/lib/security/cacerts) or the java which is used to execute jicofo (/opt/java/32/jdk1.8.0_181/jre/lib/security/cacets)?

I don't know off the top of my head, sorry. 

The bridge connects to prosody via 5222/tls. Jicofo currently has two connections to prosody -- via 5222/tls (the one that sometimes fails verification for you), and via 5347 (which the one `FocusComponent` complains about and has no tls). The second one is not open according to your nmap log. 

Note that we have a PR open to remove the second connection.

**Comment by de-johannes** [comment]
I have the same problem with the latest jicofo-docker image, even with "Alway_trust_mode" to "on".

I rolled jicofo (and only jicofo) back to jitsi/jicofo:stable-5142-4 and it is working again. 

So, for me, there seems to be a bug in there.

**Comment by bgrozev** [comment]
The xmpp component (port 5347) is no longer used
