### ISSUE TITLE
Health Check Timeout, unable to create new nativ thread

### ISSUE THREAD

**Issue by iak92** [jitsi/jicofo#687]
## Description
I installed jitsi on an Ubuntu 18.04 server out of the repository. Using apache2 as server. When restarting jicofo jitsi running for some time. After a while in a new conference the Audio and Video is missing.

## Current behavior
No Audio/Video in conference, after jicofo is running for about 30 min.

## Expected Behavior
Normal Audio/Video

## Possible Solution
Clean restart of jicofo helps for a short time.

## Steps to reproduce
Install jitsi-meet from Ubuntu repo with apache as server.
Try a new Conference, works fine.
Close conference and wait some time
No Audio and Video in new conference

# Environment details
Ubuntu 18.04
Apache2 2.4.46
jicofo 1.0-692-hf-1
jitsi-meet 2.0.5390-3                    
jitsi-meet-prosody 1.0.4628-1                                        
jitsi-meet-web 1.0.4628-1                                        
jitsi-meet-web-config 1.0.4628-1                                       
jitsi-videobridge2 2.1-416-g2f43d1b4-1         

# Log 
`Jicofo 2021-01-26 13:40:32.929 SCHWERWIEGEND: [509] org.jitsi.jicofo.Main.log() An uncaught exception occurred in thread=Thread[Jicofo Scheduledpool-2-thread-417,5,main]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2021-01-26 13:40:47.929 WARNUNG: [548] org.jitsi.jicofo.bridge.JvbDoctor.log() jvbbrewery@internal.auth.url.de/09eaf3ed-03ac-4316-8140-7ef0d84e08e2 health-check timed out, but will give it another try after: 5000
Jicofo 2021-01-26 13:41:07.930 WARNUNG: [548] org.jitsi.jicofo.bridge.JvbDoctor.log() Health check timed out for: jvbbrewery@internal.auth.url.de/09eaf3ed-03ac-4316-8140-7ef0d84e08e2
`

**Comment by damencho** [comment]
What is the server configuration? The available ram?
For running everything in one box the recommended default is 8GB.

**Comment by damencho** [comment]
Please, when you have problem or questions use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
Actually, it can be and too low number of tasks for the jicofo user, thanks @bgrozev 
What is the output of: `systemctl status jicofo`?

**Comment by iak92** [comment]
# systemctl status jicofo
`● jicofo.service - LSB: Jitsi conference Focus
   Loaded: loaded (/etc/init.d/jicofo; generated)
   Active: active (running) since Tue 2021-01-26 11:23:00 CET; 7h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9492 ExecStop=/etc/init.d/jicofo stop (code=exited, status=2)
  Process: 9661 ExecStart=/etc/init.d/jicofo start (code=exited, status=0/SUCCESS)
    Tasks: 105 (limit: 105)
   CGroup: /system.slice/jicofo.service
           └─9667 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djdk.tls.ephemeralDHKeySize=2048 -Dconfig.file=/etc/jitsi/jicofo/jicofo.conf -Dnet.java.sip.communicator.SC_HO

Jan 26 11:23:00 url.net systemd[1]: Starting LSB: Jitsi conference Focus...
Jan 26 11:23:00 url.net systemd[1]: Started LSB: Jitsi conference Focus.
`
#Host Server
Virtual Server with 16GB of Ram and 6 Cores

**Comment by damencho** [comment]
>     Tasks: 105 (limit: 105)

This is too low. That's your problem. Try setting it to some value 4096 or something. Check https://jitsi.org/qi search for `Systemd/Limits` there the example is jvb, but you can use those settings and for jicofo.
