### ISSUE TITLE
Health check gives status 404

### ISSUE THREAD

**Issue by joushx** [jitsi/jicofo#694]
## Description

The health check gives HTTP status 404

## Current behavior

The health check gives HTTP status 404

## Expected Behavior

The health check should give a status based on the application health

## Steps to reproduce

1. Set `org.jitsi.jicofo.health.ENABLE_HEALTH_CHECKS=true` and `jicofo.health.enabled=true` in the properties file
2. Start jicofo `1.0-690-1`
3. Open `http://localhost:8888/about/health`

# Environment details

* Version `1.0-690-1`
* Docker container running inside Kubernetes cluster

The health check worked as expected in previous versions (e.g. `1.0-644-1`)

**Comment by bgrozev** [comment]
>     1. Set `org.jitsi.jicofo.health.ENABLE_HEALTH_CHECKS=true` and `jicofo.health.enabled=true` in the properties file

Which file(s) did you put these in (only one of them should be sufficient)?

**Comment by joushx** [comment]
We put it into `/defaults/sip-communicator.properties`, but I just found out that this file isn't used any more. There is now a `jocofo.conf`.
