### ISSUE TITLE
ColibriThreadingTest.testColibriMultiThreading failing for power(ppc64le)

### ISSUE THREAD

**Issue by asellappen** [jitsi/jicofo#696]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

I have seen the same issue in https://community.jitsi.org/t/jitsi-dev-building-jicofo/11561 ,is this taken care ?

## Description
I am working for IBM to port ppc64le arch to the package ,during the porting i have come across the issue in one of the testing for the package jicofo, It fails as below

[ERROR]   ColibriThreadingTest.testColibriMultiThreading:158 Endpoints that have failed to send their request: [peer0, peer2, peer3, peer4, peer5, peer6, peer7, peer8, peer9, peer10, peer11, peer12, peer13, peer14, peer15, peer16, peer17, peer18, peer19]
[ERROR] Errors:

## Current behavior

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ColibriThreadingTest.testColibriMultiThreading:158 Endpoints that have failed to send their request: [peer0, peer2, peer3, peer4, peer5, peer6, peer7, peer8, peer9, peer10, peer11, peer12, peer13, peer14, peer15, peer16, peer17, peer18, peer19]
[ERROR] Errors:
[ERROR]   AdvertiseSSRCsTest.testDuplicatedSSRCs:220 ? Runtime User1 - wait for invite t...
[ERROR]   AdvertiseSSRCsTest.testOneToOneConference:84 ? Runtime User1 - wait for invite...
[ERROR]   AdvertiseSSRCsTest.testSSRCLimit:296 ? Runtime User1 - wait for invite timeout
[ERROR]   AdvertiseSSRCsTest.testSourceRemoval:163 ? Runtime User1 - wait for invite tim...
[ERROR]   BundleTest.testBundle:89 ? Runtime user1 - wait for invite timeout
[ERROR]   ColibriTest.testChannelAllocation:93 ? Timeout Timed out waiting for a respons...
[ERROR]   LeakingRoomsTest.testOneToOneConference:102 ? Runtime User2 - wait for invite ...
[ERROR]   RolesTest.testPassModeratorRole:79 ? Runtime User0 - wait for invite timeout
[INFO]
[ERROR] Tests run: 119, Failures: 1, Errors: 8, Skipped: 0

## Expected Behavior
Not expected the failure 

## Possible Solution
---

## Steps to reproduce
ran the below on ppc64le (power ) machine
 mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 mvn test -B

# Environment details
ppc64le cpu architecture lunix and ubunu  dist focal 
root@463e6e572de8:/jicofo# uname -a
Linux 463e6e572de8 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:00 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux

**Comment by bgrozev** [comment]
Can you share the full log file and the exact version of jicofo you're building?

**Comment by asellappen** [comment]
I think this was already raised by my teammate at issue https://github.com/jitsi/jicofo/issues/581.

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ColibriThreadingTest.testColibriMultiThreading:158 Endpoints that have failed to send their request: [peer1, peer2, peer3, peer4, peer5, peer6, peer7, peer8, peer9, peer10, peer11, peer12, peer13, peer14, peer15, peer16, peer17, peer18, peer19]
[ERROR] Errors: 
[ERROR]   AdvertiseSSRCsTest.testDuplicatedSSRCs:220 » Runtime User1 - wait for invite t...
[ERROR]   AdvertiseSSRCsTest.testOneToOneConference:84 » Runtime User1 - wait for invite...
[ERROR]   AdvertiseSSRCsTest.testSSRCLimit:296 » Runtime User1 - wait for invite timeout
[ERROR]   AdvertiseSSRCsTest.testSourceRemoval:163 » Runtime User1 - wait for invite tim...
[ERROR]   BundleTest.testBundle:89 » Runtime user1 - wait for invite timeout
[ERROR]   ColibriTest.testChannelAllocation:93 » Timeout Timed out waiting for a respons...
[ERROR]   LeakingRoomsTest.testOneToOneConference:102 » Runtime User2 - wait for invite ...
[ERROR]   RolesTest.testPassModeratorRole:79 » Runtime User0 - wait for invite timeout
[INFO] 
[696_issuelog.txt](https://github.com/jitsi/jicofo/files/6026817/696_issuelog.txt)

**Comment by fahimfoysal2** [comment]
**I got the same error...** on my Apple - m1, while trying to build **tag-644**: 

[ERROR] Failures: 
[ERROR]   ColibriThreadingTest.testColibriMultiThreading:161 Endpoints that have failed to send their request: [peer0, peer2, peer3, peer4, peer5, peer6, peer7, peer8, peer9, peer10, peer11, peer12, peer13, peer14, peer15, peer16, peer17, peer18, peer19]
[ERROR] Errors: 
[ERROR]   AdvertiseSSRCsTest.testDuplicatedSSRCs:241 » Runtime User1 - wait for invite t...
[ERROR]   AdvertiseSSRCsTest.testOneToOneConference:89 » Runtime User1 - wait for invite...
[ERROR]   AdvertiseSSRCsTest.testSSRCLimit:329 » Runtime User1 - wait for invite timeout
[ERROR]   AdvertiseSSRCsTest.testSourceRemoval:176 » Runtime User1 - wait for invite tim...
[ERROR]   BundleTest.testBundle:97 » Runtime user1 - wait for invite timeout
[ERROR]   ColibriTest.testChannelAllocation:102 » Timeout Timed out waiting for a respon...
[ERROR]   JicofoConfigTest » InvocationTarget
[ERROR]   LeakingRoomsTest.testOneToOneConference:102 » Runtime User2 - wait for invite ...
[ERROR]   RolesTest.testPassModeratorRole:90 » Runtime User0 - wait for invite timeout
[ERROR]   JibriDetectorTest » InvocationTarget
[ERROR]   JibriSessionTest » InvocationTarget


**Any update on this?**

**Comment by bgrozev** [comment]
It's probably a race condition because of the way the test is written (a thread expects something to happen within 1 second). I've had it on my list to fix, but haven't gotten to it. Does it happen if you rerun the test?

**Comment by bgrozev** [comment]
This was fixed recently
