### ISSUE TITLE
Shibboleth / HTTP header sso authentification with lemonldap fails 

### ISSUE THREAD

**Issue by jnfohr** [jitsi/jicofo#724]
## Description
---

The latest version of jitsi seems to have broken the ability to use lemonldap http header SSO authentication for hosts.
The following documentation was followed and worked flawlessly until yesterday's upgrade (protecting the /login/ url with lemonldap after configuring shibboleth auth):
https://lemonldap-ng.org/documentation/2.0/applications/jitsimeet.html

## Current behavior
---
Currently no redirection to lemonldap auth portal is done and the classic jitsi meet authentication form appears

## Expected Behavior
---
Redirection to lemonldap aud use of provided mail http headers as authentication .

Could you indicate what change breaks the previous behaviour?

Thanks & regards

Jean-Noël Fohr

**Comment by damencho** [comment]
@daimoc I know you are using shibboleth and have a way to test this. Can you confirm the same?

**Comment by bgrozev** [comment]
What is the latest known working and the first broken version of jicofo?

**Comment by jnfohr** [comment]
The issue follows yesterday's jitsi stable update.
So for jicofo:
- Last known working version: 1.0-692-hf-1
- Broken version: 1.0-740-1

**Comment by bgrozev** [comment]
Can you also share jocofo logs?

**Comment by jnfohr** [comment]
Here's a start log, i do not get any other message 

[jicofo_start.log](https://github.com/jitsi/jicofo/files/6326846/jicofo_start.log)

**Comment by daimoc** [comment]
Hi @damencho, I reproduce this issue  and it seems that it is an issue on the javascript side maybe link to this commit : https://github.com/jitsi/jitsi-meet/pull/8869/commits.
The redirection to the external auth url is'nt done anymore in the browser when we activate the org.jitsi.jicofo.auth.URL=shibboleth:default in jicofo configuration.
There is also a subject in the community forum for this issue : https://community.jitsi.org/t/struggling-with-shibboleth-auth-in-update-2-0-5765/97824/6.
Regards,
Damien.

**Comment by damencho** [comment]
Thank you, we will take a look next week.

**Comment by damencho** [comment]
To update the history https://github.com/jitsi/jitsi-meet/issues/9026

**Comment by bgrozev** [comment]
There's another thread here, where people have traced it to a commit in jitsi-meet:
https://community.jitsi.org/t/struggling-with-shibboleth-auth-in-update-2-0-5765/97824/8

Someone from our team will be taking a look next week.

**Comment by damencho** [comment]
As @daimoc pointed in the community forum this was broken from the UI change, I manage to repro without touching jicofo. We are working on it.
