### ISSUE TITLE
Sporadically, some users don't hear all other user' audio

### ISSUE THREAD

**Issue by magical-inference** [jitsi/jicofo#756]
## Description
in conferences with more than two participants (i.e. no p2p-conferences), sometimes not every participant receives audio by every other participant.

example: in some conference with five participants, participants 1-4 hear everyone, but number 5 doesn't receive the audio stream by one participant (say, number 3). note that the statement about the audio stream is an assumption - we don't know what exactly fails, or why. things seem to point in the direction of signaling and state management.

as of now, we can't reliably reproduce the problem, but it occurs with significant regularity.

when a participant A can't hear some different user, he can resolve the issue by reloading the page himself.
when participant B reloads the page after A couldn't hear him, A is able to hear him, too - so the affected user is able to hear participants if they reload the page.
in at least one case, after A reloaded the page, he wasn't able to hear anyone afterwards (until the other participants reloaded).

some users report that they stopped using chrome because of this, indicating a higher stability in safari, but this might be bias.

running jitsi-meet and jicofo on the latest versions, respectively (2.0.5963).

## Current behavior
Sometimes, some users don't hear specific different users - or none at all

## Expected Behavior
Every user can always hear all other users (so long as they send audio :-))

## Possible Solution
Workaround: reloading the page, works a) if the affected user themself reload the page, and b) if the users the affected user can't hear reload the page

## Steps to reproduce
Start conference with >2 users, repeat until some user can't hear some different user (or, again, no users at all)

## Environment details
Jitsi and Jicofo v 2.0.5963
Prosody 0.11.9
JVB 2.0.5963
running on Ubuntu 20.04.2 LTS

##  Disclaimer
We are not 100% sure wether this is a jicofo-issue, both the jitsi-meet and the jicofo-logs don't indicate the actual problem.

**Comment by bgrozev** [comment]
This is unlikely a problem in jicofo. Discuss on community.jitsi.org
