### ISSUE TITLE
Jicofo return item_not_found when calling Jibri SIP

### ISSUE THREAD

**Issue by veratiz** [jitsi/jicofo#796]
## Description
---
Jicofo return item_not_found when calling Jibri SIP. In Jibri logs I don't see any reqeuests.

## Current behavior
---
When I calling test sip client from jitsi-meet, application send IQ:

`<iq to="612a7a1a0bec1219b26c6a5c@muc.jitsi.test/focus" type="set" xmlns="jabber:client" id="c6a03771-076b-4a93-90ae-24ee5cb1e3fb:sendIQ"><jibri xmlns="http://jitsi.org/protocol/jibri" action="start" sipaddress="10.10.18.152" displayname="test"/></iq>`

and receive this response:

`<iq xmlns="jabber:client" from="612a7a1a0bec1219b26c6a5c@muc.jitsi.test/focus" id="c6a03771-076b-4a93-90ae-24ee5cb1e3fb:sendIQ" type="error" to="61577aca-cd2f-46e8-bff8-9a66d754b548@jitsi.test/rhdXeNRI"><error type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>`

## Expected Behavior
---

Jicofo must send IQ to Jibri when I invite sip client.

## Possible Solution
---

`diff --git a/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java b/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java`
`index ee7ece56..09a877bc 100644`
`--- a/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java`
`+++ b/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java`
`@@ -2358,9 +2358,9 @@ public IqProcessingResult handleJibriRequest(@NotNull IqRequest<JibriIq> request`
`             {`
`                 result = jibriRecorder.handleJibriRequest(request);`
`             }`
`-            if (!(result instanceof NotProcessed) && jibriSipGateway != null)`
`+            if (result instanceof NotProcessed && jibriSipGateway != null)`
`             {`
`-                result = jibriRecorder.handleJibriRequest(request);`
`+                result = jibriSipGateway.handleJibriRequest(request);`
`             }`
`         }`
`         return result;`

## Steps to reproduce
---

Just try invite sip client from jitsi-meet.

# Environment details
---

**Comment by bgrozev** [comment]
Thanks for the report and suggested fix!

**Comment by bgrozev** [comment]
Fixed in #796
