### ISSUE TITLE
`/usr/share/jicofo/jicofo.jar/reference.conf` not shipped

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jicofo#840]
`/etc/jitsi/jicofo/jicofo.conf` references `/usr/share/jicofo/jicofo.jar/reference.conf`:

https://github.com/jitsi/jicofo/blob/8c97083faa1fae60bb74c3b2f08004758930876f/debian/postinst#L93-L96

But the file under that path does not exist. There is no directory but a JAR file:

    $ ls -lh /usr/share/jicofo/jicofo.jar
    -rw-r--r-- 1 root root 608K Nov 23 00:06 /usr/share/jicofo/jicofo.jar

**Comment by saghul** [comment]
I think that's just `/usr/share/jicofo/` don't you have it there?

**Comment by paulmenzel** [comment]
Is it there on your system?

    $ ls /usr/share/jicofo/
    collect-dump-logs.sh  jicofo.jar  jicofo.sh  lib

**Comment by damencho** [comment]
`See /usr/share/jicofo/jicofo.jar/reference.conf for #available options, syntax, and default values. `
This means that if you extract the jar file you will find the reference.conf in there. 

![image](https://user-images.githubusercontent.com/3263098/143058117-97715083-ad18-4e78-8b63-720981782069.png)


Or you can check the latest version here https://github.com/jitsi/jicofo/blob/master/src/main/resources/reference.conf which may not be the same as the one coming with the version of jicofo you are running.

**Comment by paulmenzel** [comment]
After some time, I figured it out, but it’s not what is written in the comment. Having a path there means, it’s a file in the directory and not some archive.

> See `reference.conf` in the JAR file `/usr/share/jicofo/jicofo.jar` …

would be unambiguous. But `jar` is not installed by default on a Jitsi installation.
