### ISSUE TITLE
After update, entering room fails with "Unfortunately, something went wrong" (`Focus error`)

### ISSUE THREAD

**Issue by doobry-systemli** [jitsi/jicofo#849]
After upgrading to jitsi-meet from 2.0.6433-1 to 2.0.6726-1 (and jicofo 1.0-813-1 to 1.0-832-1 and jitsi-prosody 1.0.5415-1 1.0.5675-1 and jitsi-videobridge from 2.1-570-gb802be83-1 to 2.1-595-g3637fda4-1), joining a room always fails with the following JS console error:

> 2021-12-13T21:14:44.167Z [modules/xmpp/moderator.js] <7273/Ls.prototype.setFocusUserJid>:  Focus jid set to:  undefined Logger.js:154:22
> 2021-12-13T21:14:44.167Z [modules/xmpp/moderator.js] <7273/Ls.prototype.createConferenceIq>:  Session ID: null machine UID: 79bf704a9f8636b182f9ddc68b1c451a Logger.js:154:22
> 2021-12-13T21:14:44.277Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: Focus error, retry after 2000 Script: null Line: null Column: null StackTrace:  7273/Ls.prototype._allocateConferenceFocusError@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:382464
7273/Ls.prototype.allocateConferenceFocus/</<@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:381505
9230/sendIQ/a<@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:180796
run@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:176095
9230/_dataRecv/<@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:184533
forEachChild@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:167763
_dataRecv@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:184382
_onRequestStateChange@https://meet-next.example.org/libs/lib-jitsi-meet.min.js?v=5675:2:204366

Entering the preview view works as expected, only entering the room fails.

No errors are logged to either of `prosody.log`, `syslog`, `jicofo.log` or `jvb.log`.

In `prosody.log`, the following is logged when trying to enter a room:

> Dec 13 23:39:25 mod_bosh	info	New BOSH session, assigned it sid 'a052ed6d-b996-487c-9205-95cca69707e7'
Dec 13 23:39:25 bosha052ed6d-b996-487c-9205-95cca69707e7	info	Authenticated as imfpzaaibnaictjc@meet-next.example.org

Any idea what could be the problem or how to further debug? Thanks in advance for any hints :slightly_smiling_face:

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
Do you see any errors when restarting prosody?

**Comment by doobry-systemli** [comment]
Thanks for your feedback @damencho, it's highly appreciated. To be honest, we're a bit lost with the problem.

> Please, when you have questions or problems use the community forum before opening new issues, thank you.

I opened a thread in the community forum now: https://community.jitsi.org/t/after-update-entering-room-fails-with-unfortunately-something-went-wrong-focus-error/108930

> Do you see any errors when restarting prosody?

Not in `prosody.log`, but `jvb.log` logs some errors at prosody restart:

> 2021-12-14 00:07:18.609 WARNING: [59] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[jvb@auth.meet-next.example.org/ayGwZ2YG] (0) closed with error
> org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
> <stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:981)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> 2021-12-14 00:07:18.611 WARNING: [59] [hostname=localhost id=shard] MucClient$2.connectionClosedOnError#319: Closed on error:
> org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
> <stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:981)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> 2021-12-14 00:07:19.588 WARNING: [27] [hostname=localhost id=shard] MucClient.setPresenceExtensions#445: Cannot set presence extension: not connected.
> 2021-12-14 00:07:20.864 WARNING: [21] [hostname=localhost id=shard] MucClient$MucWrapper.leave#703: Error while trying to leave a MUC: 
> org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from jvbbrewery@internal.auth.meet-next.example.org/631f3066-ab30-468d-b3b6-dec1371005ed: XMPPError: item-not-found - cancel
>         at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:171)
>         at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:165)
>         at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:284)
>         at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:228)
>         at org.jivesoftware.smackx.muc.MultiUserChat.leave(MultiUserChat.java:795)
>         at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.leave(MucClient.java:699)
>         at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.join(MucClient.java:729)
>         at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.access$200(MucClient.java:662)
>         at org.jitsi.xmpp.mucclient.MucClient.joinMucs(MucClient.java:348)
>         at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:645)
>         at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)

`jicofo.log` also gets some errors:

> Jicofo 2021-12-14 00:07:18.613 WARNING: [240] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[focus@auth.meet-next.example.org/focus] (0) closed with error
> org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
> <stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:981)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
>         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> Jicofo 2021-12-14 00:07:18.622 SEVERE: [240] [xmpp_connection=client] XmppProviderImpl$XmppConnectionListener.connectionClosedOnError#397: XMPP connection closed on error: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
> <stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>

To me they look like temporary connection errors because prosody is down during the restart, but it's very likely that I missinterpret them :grimacing: 

When restarting jitsi-videobridge or jicofo, no errors are logged.

**Comment by bgrozev** [comment]
My suspicion is that something related to client_proxy failed during the update process. Can you see if you have "focus.DOMAIN" as an entry in the "focus" user in `/var/lib/prosody/auth%2eDOMAIN/focus.dat`? E.g. I have the following:
```
$ cat /var/lib/prosody/auth%..../roster/focus.dat
return {
	[false] = {
		["pending"] = {};
		["version"] = 2;
	};
	["focus....."] = {
		["groups"] = {};
		["subscription"] = "from";
	};
};
```

**Comment by xshadow** [comment]
@bgrozev I can confirm, that adding the part you mention is solving the issue.

**Comment by xshadow** [comment]
If I remember correct, the deletion of the user was necessary in the past, because there was a change in the password scheme.

**Comment by damencho** [comment]
The missing part that @bgrozev pointed out is already handled by the postinst script https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L170. 

Not sure whether that ansible is using it, if not it should use it or try to follow anytime there are changes in the postinst scripts
