### ISSUE TITLE
README 1st paragraph is very confusing to anyone new

### ISSUE THREAD

**Issue by ian-kelling** [jitsi/jicofo#859]
First sentence implies that "a server side focus" is a noun which I should understand. Web search for jitsi focus didn't lead to a definition. Eventually, I found https://xmpp.org/extensions/xep-0340.html#terms. That should be linked in the first sentence, or it should be called an XMPP focus agent.

"managing media sessions between each of the participants and the videobridge" is unclear. Read literally, it reads that it is managing media sessions from every participant to every other participant, and also managing the videobridge (no media session, just the video bridge as a separate thing it is managing), but the way it is written seems to imply there is something else going on.

"Whenever new conference is about to start an IQ is sent to the component to allocate new focus instance." 

What is "the component"? Is that this program? What is an "IQ"? Once I realized these are probably xmpp terms, only then did a web search lead somewhere. It should be called an XMPP IQ here.

"After that special focus participant joins Multi User Chat room." has bad grammar. It seems likely it should be: "After that, a special focus participant joins Multi User Chat room." What is this "Multi User Chat room"? It needs an explanation.

"It will be creating Jingle session between Jitsi videobridge and the participant." If "it" is from the previous sentence, it is unclear if the "it" is the Multi User Chat room or the focus participant. Use the actual name of what is being referred to instead.

**Comment by paweldomas** [comment]
Hi! thanks for deep analysis of the text 😅  feel free to open PR with improvements and we can take it from there

**Comment by bgrozev** [comment]
The README is very outdated and a lot of the information in it is wrong. I think it needs a near complete re-write.

**Comment by bgrozev** [comment]
We updated the readme
