### ISSUE TITLE
Jicofo reinvite Jigasi transcriber on failure

### ISSUE THREAD

**Issue by bdronneau** [jitsi/jicofo#916]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Hello,

I'm testing a failure use case of Jigasi. When Jigasi is transcribing in a conference, I restart the container, notification is correctly see in Jitsi Meet interface. But it's not possible to reinvite Jigasi after complete restart.

In code, I did not see any use case to put [active](https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/jigasi/TranscriberManager.java#L79) to `false` when Jigasi leave without be requested.

Community thread => https://community.jitsi.org/t/reinvite-jigasi-on-failure/114332

## Current behavior
---
Transcriber do not return to the conference

## Expected Behavior
---
Transcriber should return in the conference

## Possible Solution
---

## Steps to reproduce
---

- Activate subtitles
- restart Jigasi container
- activate subtitles => nothing append

# Environment details
---

Usage of https://github.com/jitsi/docker-jitsi-meet
Versions:
- Jicofo / Jigasi  / prosody stable_7001
- Meet stable_7287

**Comment by bdronneau** [comment]
Little feedback.

I've try in https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java#L833
to check if it's jigasi with
```java
if (participant.getChatMember().isJigasi())
{
    // make something
}
```

But it's not detected as Jigasi.

**Comment by bgrozev** [comment]
> But it's not detected as Jigasi.
> 
> So maybe, there is a trouble in my configuration on Jigasi advertising

I can reproduce with jigasis in our environment, I think it's because jigasi advertises `<features xmlns='http://jabber.org/protocol/disco#info'>` instead of `<features xmlns='jabber:client'>`

**Comment by bgrozev** [comment]
The only (other) effect of this bug is that jigasi's without "unmute" support will be muted anyway. But jigasi has supported "unmute" for a long time, so in practice there are no bad effects. We'll fix it in jigasi, you can patch it yourself here:
https://github.com/jitsi/jigasi/blob/master/src/main/java/org/jitsi/jigasi/JvbConference.java#L170

**Comment by bdronneau** [comment]
Hey,

I will give a try and make a feedback

**Comment by bdronneau** [comment]
Hey @damencho 
In https://github.com/jitsi/jigasi/commit/150cc9a82816c8fd65f45bf602d63e4e084b24d0 I see you have refactoring this part of code. Do you think this will close this issue ?

**Comment by damencho** [comment]
Yep
