### ISSUE TITLE
Bridge stress level unaffected by RecentlyAddedEndpoints, participants assigned to single videobridge

### ISSUE THREAD

**Issue by ubivent-seuffert** [jitsi/jicofo#943]
## Description
- Jitsi has several BridgeSelectionStrategies. In most cases the Bridge stress level is an important measurement for distributing the users across JVBs. In the event that many users join conferences at the same time, the reported bridge stress level might still be ZERO. To take that into account, the Bridge stress level in jicofo should be calculated by also looking at the recently added enpoints for that videobridge. (`Bridge.java / endpointAdded() / newEndpointsRate / getRecentlyAddedEndpointCount() / getStress()`)
---

## Current behavior
- many clients that connect at the same time will be assigned to the same JVB, even though several bridges are available
- `getStress()` (Bridge.java) will report a value of ZERO, until the reported stress level by the JVB is getting higher.
- the function `endpointAdded()` in `Bridge.java` is never called, thus the stress level calculation is not increased during this "warmup" phase while participants are still connecting. 
- this seems to be a problem since the removal of colibriv1 and the introduction of the new KOTLIN code . no call to `endpointAdded()` since then
---

## Expected Behavior
- if many participants join a conference at the same time, they should be equally assigned to available JVBs , even during the connecting/warmup phase.
- `endpointAdded()` in the `Bridge.java` is called, so that `newEndpointsRate` correctly reflects the new connection count.
- `getStress()` (Bridge.java) should show an increased value, even though the reported stress value (by the JVB) is still zero
---

## Possible Solution
- re-add the call to `Bridge.java:endpointAdded()` ( was dropped in ´remove colibri1` here https://github.com/jitsi/jicofo/commit/a64005759f9408b92648f9f8cabc3f6f8e77da9e#diff-fdf1660ca0fe2583b829d19a6e6129dee7d8509eb7bab4a42ed75d2b9d65e481L130)
---

## Steps to reproduce
- create a jitsi setup with multiple JVBs and e.g. an `IntraRegionBridgeSelectionStrategy`
- if many users connect at virtually the same time (e.g. redirect from a webcast to breakout rooms) , all participants will end up on the same JVB
---

# Environment details
- current jitsi version `2.0.7439` 
- multiple videobridges running on an AWS environment
---

As a temporary workaround i created a BridgeSelectionStrategy with a random factor added to the stress level of all bridges that have the same reported stress level 
* https://github.com/ubivent-seuffert/jicofo/blob/jitsi-meet_7439_bridgeRandom/src/main/java/org/jitsi/jicofo/bridge/IntraRegionRandomBridgeSelectionStrategy.java). 

This worked for our events and participants were evenly distributed over all existing JVBs, even if all participants connected virtually at the same time. This workaround is not meant as a permanent solution, but might give you a hint on the existing problem. (https://github.com/ubivent-seuffert/jicofo/commits/jitsi-meet_7439_bridgeRandom)

**Comment by bgrozev** [comment]
Will look into this in more detail later, but I think you're spot-on that the reomval of the call to `endpointAdded` introduced the issue.
