### ISSUE TITLE
Jicofo stats do not clean up after update to jicofo 1.0-940-1

### ISSUE THREAD

**Issue by holzi1005** [jitsi/jicofo#998]
After updating to the latest version of jicofo, the stats API does not cleanup the number of participants.
When all participants left the room, the number of conferences went to 0 but the number of particiants stays at more than 1. 
After restarting jicofo the participants drop to 0 until the next conference starts.

### Stats
There is the json of the jicofo stats_api of one jicofo server where we can see that the conferences: 0 and participants: 1:
`
{"largest_conference":4,"conference_sizes":{"average":4.0,"max":4,"min":0,"total_value":4,"total_count":1,"discarded":0,"buckets":{"0_to_1":0,"1_to_2":0,"2_to_3":0,"3_to_5":1,"5_to_10":0,"10_to_20":0,"20_to_50":0,"50_to_100":0,"100_to_200":0,"200_to_300":0,"300_to_400":0,"400_to_500":0,"500_to_max":0,"p99_upper_bound":-1,"p999_upper_bound":-1}},"total_conferences_created":205,"threads":30,"total_participants_no_source_name":11,"jingle":{"received":{"session-info":5,"session-accept":631,"session-terminate":94,"source-add":282,"source-remove":69,"transport-info":620},"sent":{"session-initiate":638,"session-terminate":50,"source-add":2172,"source-remove":187}},"bridge_failures":{"participants_moved":0},"total_participants_no_multi_stream":11,"total_participants":565,"participant_notifications":{"ice_failed":0,"request_restart":94},"queues":{},"jigasi":{},"bridge_selector":{"total_least_loaded_in_region_group":0,"lost_bridges":0,"total_not_loaded_in_region_in_conference":506,"in_shutdown_bridge_count":0,"total_not_loaded_in_region_group":0,"operational_bridge_count":5,"total_not_loaded_in_region_group_in_conference":0,"total_least_loaded_in_region_group_in_conference":0,"total_least_loaded":0,"total_least_loaded_in_region":0,"total_split_due_to_load":0,"total_least_loaded_in_region_in_conference":0,"total_not_loaded_in_region":132,"total_split_due_to_region":0,"bridge_version_count":1,"bridge_count":5,"total_least_loaded_in_conference":0},"jibri":{"total_sip_call_failures":0,"live_streaming_active":0,"total_recording_failures":0,"sip_call_active":0,"total_live_streaming_failures":0,"recording_active":0},"endpoint_pairs":16,"conferences":0,"participants":4}
`

### Grafana Dashboard
![Unbenannt](https://user-images.githubusercontent.com/58698758/197932463-fbc85925-5bee-4c7f-be24-9f88a800118b.PNG)

### Infrastructure:
3 Shards: All Ubuntu 20.04
3 Jicofos: 1.0-940-1
3 Procody Server: 0.11.10-1 (Manuell installed)
5 Videobridges
2 Turnserver

Eerything has been updated at the weekend to the lates version of Jitsi

**Comment by bgrozev** [comment]
Thanks for the report. This is fixed in master, see #995 and #996. 

Note that the failure to update the metrics only occurs while jicofo has 0 conferences, so stats for machines that are in use are still reliable.
